flux-framework/flux-accounting

- AUTHORS
- CONTRIBUTING.md
- COPYING
- LICENSE
- NOTICE
- NOTICE.LLNS
- cmd/fairshare.py
- cmd/fs_unittest.py
- src/create_db.py
- src/write_jobs.py
As mentioned in #3, none of the files in the repository contain a Copyright header:
```
###############################################################
...
```
This PR adds the header to all of the source files in the repo, as well as adds the licensing documents and appropriate symlinks to the repository.
> repo: Add licensing documents, copyright headers to files

- .gitignore
- Makefile
- README.md
- accounting/test/docker/centos8/Dockerfile.centos8
- accounting/test/docker/ubuntu/Dockerfile.ubuntu
- tox.ini
Noted by @dongahn in #6 and #12, the install and unit test instructions in the **README.md** were not clear/non-existent. This PR adds a **Makefile** that installs the dependencies listed in **requirements.txt** as well as runs the unit tests, so both can be run with `make check`.
```
$ make check
pip3 install -r requirements.txt
Collecting pandas==0.25.3
Installing collected packages: pandas
Successfully installed pandas-0.25.3
python3 -m unittest discover
....
----------------------------------------------------------------------
Ran 4 tests in 0.021s
OK
```
**README.md** has also been updated to reflect these instructions. 
Fixes #12
> repo: add install instructions, Makefile to install dependencies and run unit tests 

- Makefile
- README.md
- accounting/accounting_cli.py
- accounting/accounting_cli_functions.py
- accounting/create_db.py
- setup.py
- test/test_accounting_cli.py
- test/test_create_db.py
- tox.ini
**Problem**: currently, the only way to access data within the accounting database file (**FluxAccounting.db**) is to open a sqlite3 shell from the same directory where the database file is located and run SQLite commands:
```
$ sqlite3
moussa1@trinity1 $ sqlite3
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open FluxAccounting.db
sqlite> .headers on
sqlite> .mode column
sqlite> select * from association_table;
id_assoc    creation_time  mod_time    deleted     user_name   admin_level  account     parent_acct  shares      max_jobs    max_wall_pj
----------  -------------  ----------  ----------  ----------  -----------  ----------  ----------- …
```
> accounting_cli.py: add command line interface

- Makefile
- README.md
- setup.py
This PR updates the install instructions for flux-accounting so that its commands can be picked up by Flux's command driver `flux(1)`. The repo can be pulled down and installed with `make install`, which will place **flux-account.py** in flux-core's `libexec/` directory. Then, like before, the SQLite database file can be interacted with using the command line arguments:
```
$ flux account view-user fluxuser
id_assoc  creation_time    mod_time  deleted user_name  admin_level account parent_acct  shares  max_jobs  max_wall_pj
1     1589225734  1589225734        0  fluxuser            1    acct       pacct      10       100           60
```
The instructions on how to install the package have been reflected in the **README** as well. 
Fixes #16
---
Since I have a conceptual question or two …
> make: add make install, update install instructions

- accounting/accounting_cli.py
- accounting/create_db.py
**Problem**: Both **create_db.py** and **accounting_cli.py** make assumptions about the location of the database file **FluxAccounting.db**. When **create_db.py** gets run, the database file gets placed in the same directory as the source code:
```
|-- LICENSE -> COPYING
|-- Makefile
|-- NOTICE -> NOTICE.LLNS
|-- NOTICE.LLNS
|-- README.md
|-- accounting
|   |-- FluxAccounting.db
|   |-- accounting_cli.py
|   |-- accounting_cli_functions.py
|   |-- create_db.py
```
This forces all of the subcommands to be executed in the same directory as well.
---
This PR adds a new optional command line argument `-p`, `--path` that allows the user to specify the database location when both creating the database and executing any of the subcommands. If no `-p` is passed, both scripts will default to the …
> create_db.py, accounting_cli.py: add configurable database path

- README.md
- accounting/create_db.py
- test/test_accounting_cli.py
- test/test_create_db.py
**Problem**: as discussed in #23, the current table structure of `association_table` has a **UNIQUE** constraint on the `username` field. However, there is a need for multiple entries to be created with the same username, but different accounts. 
This PR changes the structure of `association_table` to instead have a primary key of a combination of both `username` and `account`. It also removes the `assoc_id` field from the table, which will be replaced by SQLite's native `ROWID` field [[1]](https://www.sqlite.org/autoinc.html). This should allow multiple entries to be created with the same username, as long as they are under different accounts. 
Trying to add the same user under the same account should raise an `IntegrityError`:
```
$ flux account add-user --username=fluxuser …
```
> create_db: change table structure to allow duplicate usernames

- accounting/accounting_cli.py
**Problem**: In the `add-user` subcommand, all fields in the association_table in `flux-accounting` were required to be filled in when adding a new user. However, I learned that account names are unique in Slurm, so we generally don’t need to specify the parent account when adding a user (though we do need to specify a parent when adding a new account). I don’t think that we want the parent account to be a required field in `add-user`. More generally, it’d be nice to have default values for several of the add-user options.
This PR adds a default value to a number of the fields in `add-user`. The bare minimum fields required are now only `username` and `account`. The default values were set for the following fields:
- `admin-level=1`
- `parent-acct=`
- `shares=1`
- `max-jobs=1`
- …
> accounting_cli.py: add default arg values for add-user subcommand

- NEWS.md
- README.md
This PR tags the first official version of `flux-accounting` - `0.1.0`! It updates the **README.md** to reflect the changes to the usage examples (namely, removing the requirement to be in the same directory as the database file when executing any subcommands). It also adds a **NEWS.md** to track new features, bug fixes, and any deprecated features with future tags of `flux-accounting`. 
Fixes #27
> flux-accounting: release v0.1.0!

- accounting/accounting_cli.py
- accounting/accounting_cli_functions.py
- test/test_accounting_cli.py
The power finally came back on at my place! I can continue where I left off before mother nature so rudely interrupted me 😅
**Problem**: flux-core's job-archive currently stores job records in a SQLite database that can be viewed and queried with SQLite commands: 
```
sqlite> select userid,id,t_submit,t_run,t_inactive,ranks,R from jobs;
userid      id            t_submit         t_run            t_inactive        ranks       R                                                                            
----------  ------------  ---------------  ---------------  ----------------  ----------  -----------------------------------------------------------------------------
2001        429932937216  1597722545.7235  1597722545.7498  1597722545.83819  0 …
```
> job-archive: add front-end to job-archive

- accounting/accounting_cli.py
- accounting/create_db.py
This PR would probably be nice to land before our end-of-August release deadline as well. :-)
**Problem**: As mentioned in #35, in order to initially create the flux-accounting database, you have to go into the `flux-accounting` directory and call the `create_db.py` script directly:
```
[flux-framework/flux-accounting/accounting] $ ./create_db.py -p path/to/FluxAccounting.db
```
---
This PR removes `main()` from **create_db.py** and instead adds a new subcommand to **accounting_cli.py**:  `create-db`, which creates **FluxAccounting.db**. It takes one argument, the path to the database file.
```
$ flux account create-db path/to/FluxAccounting.db
```
Keeping the same behavior as before, ownership of the directory that the database file is placed in is required for the database to be …
> accounting_cli.py: add create-db subcommand

- accounting/accounting_cli.py
- accounting/accounting_cli_functions.py
- accounting/create_db.py
- test/test_accounting_cli.py
- test/test_create_db.py
This is the other PR related to the [end-of-August milestone](https://github.com/flux-framework/flux-accounting/milestone/1).
**Problem**: Currently there is only one table in the flux-accounting database, `association table`, that stores user account information. One of the fields in every record in this table is an _account_ and optional _parent account_ field, which associates a user with an account they can charge jobs against. There is no information on the the account itself, however, such as information related to how many shares it gets on a machine.
---
The first part of this PR removes the _parent_acct_ field from `association_table`, since that information would now be captured as the _parent_bank_ field in `bank_table`. 
The second part looks to add a second table to the …
> create_db.py: add bank table to Flux Accounting database 

- NEWS.md
- README.md
This PR adds the release notes for flux-accounting v0.2.0. This PR should go in after #33, #34, and #36 land.
> add flux-accounting v0.2.0 release notes

- test/test_accounting_cli.py
- test/test_bank_subcommands.py
- test/test_job_archive_interface.py
- test/test_user_subcommands.py
**Problem**: The main unit test file in `flux-accounting`, **test_accounting_cli.py** is getting quite long with all of the unit tests; there are a bunch in there and they cover three different areas of `flux-accounting`: the **user table subcommands**, the **job archive interface subcommands**, and the **bank table subcommands**. 
---
This PR breaks up **test_accounting_cli.py** into three different test files:
* **test_user_subcommands.py**
* **test_job_archive_interface.py**
* **test_bank_subcommands.py**
All four test files (I say 4 because **test_create_db.py** is also there in the `test/` directory) can still be run with `tox`, which is what I've been using to run these tests:
```
$ tox
GLOB sdist-make: /Users/moussa1/src/flux-framework/flux-accounting/setup.py
python3.6 …
```
> tests: break up test_accounting_cli.py into multiple test files

- accounting/create_db.py
- test/test_create_db.py
As mentioned in #39, the current primary key for the `bank_table` is the name of the bank, whose data type is `text`, a variable data type. Instead, it is considered best practice to use a fixed data type for a primary key (ref: [this StackOverflow post](https://stackoverflow.com/questions/15477005/what-are-the-pros-and-cons-for-choosing-a-character-varying-data-type-for-primar) that @dongahn pointed me to). 
---
This PR adds a new field to the `bank_table` called _bank_id_ which will serve as the new primary key. It is of type `int`. It will auto increment as more banks are added to this table. 
Fixes #39
> bank_table: change primary key to a fixed data type

- accounting/accounting_cli_functions.py
- test/test_bank_subcommands.py
**Problem**: Currently, `add_bank()` and `edit_bank()` impose constraints on the amount of shares sub banks can have compared to their parent bank; notably, `sum(sub_bank_shares) <= parent_bank_shares`. Thanks to @SteVwonder for first pointing this out (and to @ryanday36 for clarifying in #40), but these constraints are actually not required.
--- 
This PR removes those checks from `add_bank()` and `edit_bank()` and removes the unit tests that interacts with those constraints. 
Fixes #40
> bank_table: remove bank constraints from add_bank(), edit_bank()

- accounting/accounting_cli.py
- accounting/accounting_cli_functions.py
- accounting/print_hierarchy.py
- test/test_bank_subcommands.py
**Problem**: The current output of `print-hierarchy()` is pretty clunky and hard to read if there are lots and lots of banks and sub banks, each which might hold lots of user accounts.
In reality, with lots of banks and accounts, we need output that is cleaner and has more of a directory tree layout. 
---
This PR moves `print_hierarchy()` to its own file, **print-hierarchy.py**, and changes its output to more closely resemble the `sshare` command. For example, take the following bank structure
```
A
|
|-----|
B     C
|     |
|---| |---|
D   E F   G
```
With a call to `print-hierarchy()`, this should result in the following output:
```
Bank|User|RawShares
A||1
B||1
D||1
D|user1|1
E||1
C||1
F||1
F|user2|1
F|user3|1
G||1
G|user4|1
```
This PR is the first step to gathering bank/user data …
> print-hierarchy: improve output format

- NEWS.md
Release notes for `v0.3.0`! 
For now, this includes the two fixes that were merged (#42 and #44).  
I think #47 can just be added to next month's release since it has not been merged.
> NEWS.md: add release notes for v0.3.0

- accounting/accounting_cli.py
- accounting/accounting_cli_functions.py
- test/test_job_archive_interface.py
**Problem**: As described in #46, the current way to interact with the job-archive interface is through a series of subcommands. These, however, limit the user to only being able to run one of these filters at a time.
---
This PR turns the existing subcommands into optional arguments under a new subcommand, `view-job-records`. The filter options are the same:
```
optional arguments:
-h, --help            show this help message and exit
-u USERNAME, --user USERNAME
username
-j JOBID, --jobid JOBID
jobid
-a START TIME, --after-start-time START TIME
start time
-b END TIME, --before-end-time END TIME
end time
```
except now they can be combined (e.g. I want to see all jobs run by a user _u_ before some timestamp _t_).
The current implementation grabs the optional args passed in and performs a …
> job-archive interface: turn current subcommands into options

- accounting/accounting_cli.py
**Problem**: Trying to use the `view-job-records` subcommand would result in the following error:
```
$ flux account -p /var/lib/flux/jobs.db view-job-records 
Traceback (most recent call last):
File "/usr/libexec/flux/cmd/flux-account.py", line 11, in <module>
load_entry_point('flux-accounting==0.1.0', 'console_scripts', 'flux-account.py')()
File "/usr/lib64/flux/python3.6/flux_accounting-0.1.0-py3.6.egg/accounting/accounting_cli.py", line 204, in main
TypeError: view_job_records() takes 2 positional arguments but 3 were given
```
I think this is because `view_job_records()` was interpreting `args` as a `Namespace` object instead of unpacking it into a dictionary.
---
This PR updates the parameters passed to `view_job_records()` to: 
- the SQLite connection to the job-archive DB
- an …
> accounting_cli: change params to view_job_records

- .travis.yml
- README.md
- codecov.yml
This PR adds Travis CI and Codecov to `flux-accounting`, as well as the badges indicating successful builds and the coverage percentage to the top of the **README**.
> repo: add Travis CI, Codecov to flux-accounting

- accounting/accounting_cli.py
- accounting/accounting_cli_functions.py
- accounting/create_db.py
- accounting/print_hierarchy.py
- test/test_bank_subcommands.py
- test/test_user_subcommands.py
**Problem**: Noted in #38, there was no sort of error handling if `create-db()` failed for whatever reason while creating the database. There was also an instance in `edit-user()` where if somebody tried to edit a user's account information and specified a non-existent field, the program would call `sys.exit(1)`.
---
This PR wraps `create-db()` in a `try-except` block, and will print any SQLite operational error to the screen. It also changes `edit-user()` to raise an `Exception` instead of calling `sys.exit()` if a non-existent field is specified.
I also noticed that `accounting_cli_functions.py` had a couple of unused `import` statements, so I figured I would remove those as well in this PR (if anything, I can always open another tiny PR that removes it instead of including it in this …
> edit error handling in create-db(), edit-user()

- .gitignore
- accounting/accounting_cli.py
- accounting/create_db.py
- configure.ac
- src/fairness/Makefile.am
- src/fairness/print_hierarchy/Makefile.am
- src/fairness/print_hierarchy/print_hierarchy.cpp
- src/fairness/print_hierarchy/test-print-hierarchy.sh
This experimental PR is my C++ implementation of the `print_hierarchy()` function, which will be used to display output from the flux-accounting database.
The program is compiled with the following:
```console
g++ print_hierarchy.cpp -l sqlite3 --std=c++11 -o print_hierarchy 
```
And is called with one command line argument, a path to the flux-accounting database file:
```console
./print_hierarchy path/to/FluxAccounting.db
```
In `main()`, the program attempts to open the database file in read-write mode. Once it opens the file, it will look for a root bank (one that sits on top of the hierarchical 'tree'). The program should exit if the following cases are met:
- the `bank_table` does not have a root bank (i.e. there is no bank in the `bank_table` that does not have a `parent_bank`)
- …
> add print_hierarchy() C++ implementation to weighted tree lib

- NEWS.md
Release notes for `v0.4.0`!
The big additions include the parameter fix from #55, the move of `view_job_records()` into its own module in #57, the addition of a library that provides a weighted tree-based fairness, and automake tools to the flux-accounting repo.
> NEWS.md: add release notes for v0.4.0

- src/fairness/print_hierarchy/print_hierarchy.cpp
- src/fairness/print_hierarchy/test-print-hierarchy.sh
**Problem**: As noted in #71, a number of the `sqlite3_stmt` variables where defined in global scope. If we wanted to call `get_sub_banks()` from other parts of the codebase, we should instead move those variables inside `main()` and pass them into `get_sub_banks()`. 
---
This small PR does just that; moves the `sqlite3_stmt` variables into `main()` and reformats the function header and calls for `get_sub_banks()`. 
I also added another test to **test-print-hierarchy.sh**: when a flux-accounting database is created with no root bank, the program should detect that and exit out. 
Fixes #71
> print_hierarchy.cpp: move global variables into main(), add another test

- t/t0000-sharness.t
Problem:  The sharness tests fail if debug=t or verbose=t is set
in the environment since sub-sharness tests cannot tolerate the
extra output triggered by these variales.
Unset 'debug' and 'verbose' in sharness sub-tests to ensure they
do not add extra output in the subtests.
Copied from @grondo's commit in flux-framework/flux-core#3379
> t0000-sharness.sh: fix test with debug/verbose set in env

- src/bindings/python/flux/accounting/README.md
- src/bindings/python/flux/accounting/accounting_cli_functions.py
- src/bindings/python/flux/accounting/create_db.py
- src/bindings/python/flux/accounting/flux-account.py
- src/bindings/python/flux/accounting/job_archive_interface.py
- src/bindings/python/flux/accounting/print_hierarchy.py
- src/bindings/python/flux/accounting/test/test_create_db.py
- src/bindings/python/flux/accounting/test/test_job_archive_interface.py
- src/bindings/python/flux/accounting/test/test_user_subcommands.py
- src/fairness/print_hierarchy/print_hierarchy.cpp
- t/t1000-print-hierarchy.t
_note: this PR should probably be reviewed after #73 gets approved and landed since that is a higher priority at the moment, so I'll leave it as a Draft PR for now._ 
_note 2: there are a couple of smaller fixes that I included as a part of this PR as well - more specifically issues #67 and #70. If it is more appropriate to cut those out and post as separate PRs, I would be happy to do so._
This PR is part 1 of implementing a [Level Fairshare](https://slurm.schedmd.com/fair_tree.html) calculation into flux-accounting - calculating an effective usage factor for a given user in the flux-accounting database. It looks at a user's given jobs in the job-archive, calculates a raw usage factor (while also applying a half-life decay to that user's past job usage factors), and then divides that by …
> fairshare implementation part 1: add effective job usage factor calculation  

- src/bindings/python/flux/accounting/README.md
- src/bindings/python/flux/accounting/create_db.py
- src/bindings/python/flux/accounting/test/test_create_db.py
- src/bindings/python/flux/accounting/test/test_job_archive_interface.py
**Problem**: As noted in #84, the `job_usage_factor_table` references both the `association_table` and `bank_table`; when a bank (and its subsequent users) get removed, their job usage history will also be removed from this table. Speaking with Ryan, we should probably keep this data in case we need it at a later date.
---
This PR removes the `ON DELETE CASCADE` option from the creation of `job_usage_factor_table` so a user's job usage history is kept even when they are removed from the flux-accounting DB. I added a test that checks to see a user's entry in the `job_usage_factor_table` is still present even when they are removed from the `association_table`. 
Fixes #84
> delete_user/delete_bank: keep job usage history after deletion of user 

- src/bindings/python/flux/accounting/test/test_job_archive_interface.py
_note: this PR is built on top of #92, and should probably only be reviewed after that has landed._
**Problem**: 
Problem: The fake job-archive DB uses `time.time()` to generate the timestamps for the job records, which can sometimes create problems with testing.
---
Use `unittest.mock()` to generate the same timestamps for the job records every time the unit tests are run:
```
UserID|Username|JobID|T_Submit|T_Run|T_Inactive|Nodes|R
1001|1001|100|9998000.0 |10000000.0|10002000.0|1|{"version":1,"execution": {"R_lite":[{"rank":"0","children": {"core": "0"}}]}}
1001|1001|101|10008000.0|10010000.0|10012100.0|1|{"version":1,"execution": {"R_lite":[{"rank":"0","children": {"core": "0"}}]}}
1002|1002|102|10018000.0|10020000.0|10022000.0|2|{"version":1,"execution": …
```
> tests: integrate unittest.mock() with sample job-archive DB

- src/bindings/python/flux/accounting/accounting_cli_functions.py
- src/bindings/python/flux/accounting/create_db.py
- src/bindings/python/flux/accounting/flux-account.py
- src/bindings/python/flux/accounting/test/test_job_archive_interface.py
- src/bindings/python/flux/accounting/test/test_user_subcommands.py
As noted in #95, there were a couple of issues with the `delete-user` and `delete-bank` subcommands.
Trying to delete a user results in the following error:
```console
[fluxuser@30451d797d82 accounting-DB]$ flux account -p FluxAccounting.db delete-user user1
Traceback (most recent call last):
File "/usr/libexec/flux/cmd/flux-account.py", line 249, in <module>
main()
File "/usr/libexec/flux/cmd/flux-account.py", line 220, in main
aclif.delete_user(conn, args.username)
```
As well as the presence of a foreign key issue between the `association_table` and the `job_usage_factor_table`. Basically, when a user gets removed from the `association_table`, their entry in the `job_usage_factor_table` is no longer valid because it references the entry in the `association_table`, thus rejecting the …
> delete-user, delete-bank: add commit() to functions, add bank arg to delete-user subcommand

- configure.ac
- src/bindings/python/flux/accounting/create_db.py
- src/bindings/python/flux/accounting/job_archive_interface.py
- src/bindings/python/flux/accounting/test/test_job_archive_interface.py
~Now that #79 has landed, we can add the job usage value returned by `calc_usage_factor()` to the output of `print-hierarchy`. The output should now look like the following:~
_please see comments at the bottom of this PR thread regarding changing the structure of this PR._ 
_note: this PR also includes the re-addition of `AUTHORS`; I removed the file in #90 not realizing that it was required to build flux-accounting: so sorry about that!_
> association_table: add job usage column to association_table

- src/bindings/python/flux/accounting/flux-account.py
Problem: As noted in #89, the shebang line at the top of **flux-account.py** might lead to a Python version mismatch.
This PR removes the shebang line at the top of the file to follow flux-core's Python convention.
> flux-account.py: remove shebang line from top of file

- NEWS.md
This PR adds release notes for v0.7.0. I also noticed a small mislabel on my title for my release notes `v0.6.0` (**2020** instead of **2021**), so I added that as a commit to this PR as well.
> NEWS.md: add release notes for v0.7.0

- src/fairness/account/account.cpp
- src/fairness/account/account.hpp
- src/fairness/reader/test/data_reader_db_test01.cpp
- src/fairness/weighted_tree/test/weighted_tree_load.cpp
- src/fairness/weighted_tree/test/weighted_tree_load.hpp
- src/fairness/weighted_tree/test/weighted_tree_test01.cpp
- src/fairness/weighted_tree/weighted_tree.cpp
- src/fairness/weighted_tree/weighted_tree.hpp
- src/fairness/weighted_tree/weighted_walk.cpp
- src/fairness/weighted_tree/weighted_walk.hpp
The headers for some of the files in the fairness directory need to be updated to the new minimal header and made consistent with the other files in this repo.
This PR updates the headers of some of the files in the `fairness` directory.
> fairness: update headers of source files

- .mergify.yml
- configure.ac
- src/bindings/python/fluxacct/Makefile.am
- src/test/docker/README.md
- src/test/docker/bionic/Dockerfile
- src/test/generate-matrix.py
While working inside of the `bionic` Docker image the other day/this morning, I ran into some trouble trying to install flux-accounting and use it. More specifically, I continued to run into dependency issues both with the `accounting` module and the `pandas` dependency itself:
```console
moussa1@docker-desktop:/usr/src$ flux account -h
Traceback (most recent call last):
File "/usr/libexec/flux/cmd/flux-account.py", line 15, in <module>
import fluxacct.accounting
ModuleNotFoundError: No module named 'fluxacct'
```
After some fiddling around, I think I found that the answer included not adding the location of `/usr/lib/python3.7/site-packages/` to my `PYTHONPATH`. I think the `bionic` image could be improved by not having to perform these steps manually after the user starts up an …
> docker: change module/dependency installation in bionic image, add a README

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
- src/cmd/flux-account.py
Noted in #117, there is currently no call to the `calc_usage_factor()` function, which is responsible for calculating an association's job usage value. This is another prerequisite for our server-side plugin work, where we are periodically re-calculating both usage and fairshare values and updating them, where they'll then be used to calculate a user's job priority.
But as I was adding a new subcommand that calls `calc_usage_factor()`, I noticed myself struggling to read the function itself. The function has lots of long comments, long variable names, and lots of calls to the flux-accounting database inside the function. I didn't like how much time was spent trying to figure out what I wrote. The other issue I found was with the calculation itself. I believe some of the calculations for …
> job_archive_interface: refactor calc_usage_factor(), add job usage calculation subcommand

- src/bindings/python/fluxacct/accounting/accounting_cli_functions.py
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/test/test_create_db.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
The `association_table` currently contains two fields that have not been used with any features of flux-accounting: `max_jobs` and `max_wall_pj`. As a result of creating a set of smaller issues to handle per-user, per-job, and per-queue limits, it looks like these kinds of limits will either be handled by a mechanism other than the flux-accounting DB (I opened issue [#3652](https://github.com/flux-framework/flux-core/issues/3652) in flux-core to discuss part of these per-job limits) or changed in some way to be handled within flux-accounting. 
This PR just removes the `max_jobs` and `max_wall_pj` fields from the `association_table` to prepare for adding per-user limit support in flux-accounting.
> association_table: remove unused fields

- src/bindings/python/fluxacct/accounting/Makefile.am
- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
`accounting_cli_functions.py` contains functions for both users and banks, resulting in a pretty large source file. It would probably be cleaner to break this up into two smaller files: one that contains user subcommands and one that contains bank subcommands.
---
This PR does just that; it breaks up `accounting_cli_functions.py` into two files: `user_subcommands.py` and `bank_subcommands.py` and reflects the new changes wherever the Python modules are used.
> python: break up accounting_cli_functions.py

- .github/workflows/main.yml
- configure.ac
- src/Makefile.am
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_create_db.py
- src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
- src/plugins/Makefile.am
- src/plugins/bulk_update.py
- src/plugins/mf_priority.cpp
- src/test/checks-annotate.sh
- src/test/docker/bionic/Dockerfile
- src/test/docker/centos8/Dockerfile
- t/Makefile.am
- t/rc/rc1-job
- t/rc/rc1-kvs
- t/rc/rc3-job
- t/rc/rc3-kvs
- t/sharness.d/flux-sharness.sh
- t/t1001-mf-priority.t
This is a very early first-cut, work-in-progress PR that adds multi-factor priority calculation to flux-accounting. It is still missing a couple of integral pieces, but I thought it might be best to post it early for the following reasons:
- Since this is a somewhat important milestone for flux-accounting as a whole, I wanted to make sure I have been headed in the right direction so far with my plugin
- I think I might benefit from some collaboration and feedback on the pieces that are still missing from this plugin (testing strategy, the data structure in the plugin, managing users who belong to more than one bank, etc.)
---
A multifactor priority plugin is responsible for calculating a job's priority using a number of different factors that may help or hurt a job's overall priority. …
> plugin: add multifactor priority plugin

- t/Makefile.am
- t/scripts/send_payload.py
- t/scripts/submit_as.py
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
Currently, the sharness test for the multi-factor priority plugin tests the plugin with just a single user submitting jobs and making sure the priority calculation is behaving as expected.
As discussed in #125, it would be nice to expand this testing further to simulate a "multi-user" environment, where different users are submitting jobs against the same plugin to make sure 1) the priority calculated for submitted jobs are calculated correctly, and 2) the order in which jobs should be run are behaving as expected. @grondo very nicely wrote up a Python script that allows jobs to be submitted under an arbitrary userid. We can disable job execution using `flux queue stop` so no jobs are actually run, submit a number of jobs to the queue, and then examine the queue to make sure the ordering …
> t: add multi-factor priority order sharness tests

- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/test/test_create_db.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/plugins/bulk_update.py
- src/plugins/mf_priority.cpp
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
As discussed in #123, the "default" bank support added in #122 currently treats the first bank the user belonged to in the flux-accounting database as the default bank. It cannot be changed once the user gets added to the DB. It would be good to add more robust default bank support in both the flux-accounting database and the priority plugin, where a user's default bank could be changed by a sys admin even after they are initially added.
This PR adds a `default_bank` column to the `association_table` in the flux-accounting database. When a user/bank combination gets added to the database, a lookup is performed to see if the user already exists in the table and, if they do, what their default bank is. It will set the `default_bank` to the value of the first bank they are added to; however, …
> association_table: add "default_bank" column, change plugin's default bank behavior

- src/fairness/print_hierarchy/flux_shares.cpp
- src/fairness/reader/data_reader_db.cpp
- src/fairness/reader/data_reader_db.hpp
- src/fairness/weighted_tree/Makefile.am
- src/fairness/writer/data_writer_stdout.cpp
- src/fairness/writer/data_writer_stdout.hpp
- t/expected/custom_small_tie_parsable.txt
- t/expected/out_of_insert_order.txt
- t/expected/small_no_tie.txt
- t/expected/small_no_tie_parsable.txt
- t/expected/small_tie.txt
- t/expected/small_tie_all.txt
- t/expected/small_tie_all_parsable.txt
- t/expected/small_tie_parsable.txt
`flux_shares.cpp` currently contains its own convenience functions to print out information from a weighted tree object. 
Now that flux-accounting has the `data_writer` class, it might make more sense to move those convenience functions to a `data_writer` subclass that `flux_shares.cpp` can utilize.
This PR can be separated into three different parts.
Part 1 adds the newly-added fairshare field to `data_reader_db` so that fairshare info also gets added during the construction of a weighted tree object.
Part 2 adds a new subclass to the `data_writer` class (and to the weighted tree library): `data_writer_stdout`, which is responsible for writing flux-accounting information to stdout. It essentially moves the helper functions that used to be in `flux_shares.cpp` into this new subclass, …
> flux-shares: add data_writer_stdout subclass, add fairshare field to output

- src/bindings/python/fluxacct/accounting/create_db.py
- src/plugins/bulk_update.py
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
~~_note: this PR is built off of the changes proposed in #130, so I will leave this one as [WIP] until that one lands._~~
~~_#130 has landed, but there are a couple of questions that might alter the direction this PR takes, so I think I'll leave this PR as [WIP] until those questions are sorted out._~~
The multi-factor priority plugin added in #122 currently just calculates a user's job priority and does not enforce any kind of per-user limits like the ones laid out in #121. Some of the limits that flux-accounting has a direct impact on enforcing are the following:
**max_jobs:** max number of submitted jobs per user
**max_nodes:** max number of nodes used across all of a user's running jobs
This PR looks to add enforcement of the **max_jobs** per-user/bank combination limit to the …
> plugin: add a per-user/bank max jobs limit

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1007-flux-account.t
~~_note: this PR is built on top of #131, so I will leave this as [WIP] until that PR is merged and then I will rebase._~~
_note: this PR will round out the `0.9.0` release for flux-accounting._
I noticed while doing some interactive testing with **flux-account.py** that a couple subcommands were broken/not working as expected, mostly because of some broken function headers that came partly as a result from #124 and from a general lack of testing. This PR includes some various minor fixes to a couple of the subcommands and user/bank functions.
This PR also adds a set of tests for **flux-acount.py** to hopefully prevent bugs like this from creeping into the code in the future. These tests use the basic subcommands that interact with user and bank accounts in the flux-accounting DB, such as …
> flux-account.py: fix add-user, edit-user, edit-bank, add sharness tests for python subcommands

- src/Makefile.am
- src/cmd/Makefile.am
- src/cmd/flux_update_fshare.cpp
- src/fairness/Makefile.am
- src/fairness/reader/data_reader_base.cpp
- src/fairness/reader/data_reader_base.hpp
- src/fairness/weighted_tree/Makefile.am
- src/fairness/writer/data_writer_base.cpp
- src/fairness/writer/data_writer_base.hpp
- t/Makefile.am
- t/expected/post_fshare_update.expected
- t/expected/pre_fshare_update.expected
- t/scripts/create_test_db.py
- t/scripts/update_usage_column.py
- t/t1006-update-fshare.t
As noted in #135, there is a way to calculate fairshare values for users in a flux-accounting database using the `weighted_tree` library, but there is no implementation to call it with a front-end command and on a periodic time scale.
This is an implementation of a front-end script that will load flux-accounting information from a DB, calculate fairshare values, and write the updated information back to the DB. It utilizes both the `data_reader` and `data_writer` classes to read/write the DB information. It takes one optional argument, a path to the flux-accounting DB. If no path is passed in, it will try to load a DB path using `X_LOCALSTATEDIR`, the path set for **FluxAccounting.db** when configuring with a custom `localstatedir`.
The tests for this front-end script utilize two helper …
> cmd: add a front-end fairshare update script

- scripts/.pylintrc
- src/bindings/python/fluxacct/accounting/Makefile.am
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/qos_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_create_db.py
- src/bindings/python/fluxacct/accounting/test/test_qos_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
- t/t1007-flux-account.t
This is an early [WIP] PR for defining and configuring Quality of Service (further referred to as QoS) in the flux-accounting database. In a subsequent PR, I plan to integrate this new table with the multi-factor priority plugin, where it will be used to affect the prioritization of jobs.
QoS is a mechanism for further prioritizing submitted jobs. Each QoS has a unique name and an associated priority that can positively or negatively impact the priority of a job in a queue. Jobs that request (and are permitted) a QoS will incorporate the priority associated with that QoS in the multi-factor priority calculation. 
This PR introduces the definition and configuration of QoS in the flux-accounting DB.
QoS is primarily defined and configured via its own table in the DB, named `qos_table`. It …
> flux-accounting DB: add Quality of Service table, field in `association_table`

- t/scripts/create_test_db.py
- t/t1006-update-fshare.t
**Problem**: The path to the test DB in `create_test_db.py` is hard-coded in, which results in a `FileNotFoundError` when running the test on LC systems because I don't have permission to write files to `/usr/src`.
Change the helper script to take a command line argument which will represent a path to the DB file.
**Solution**: Use `${FLUX_BUILD_DIR}` in the sharness test when setting the path to the DB file, and set the path inside the flux-accounting directory.
Fixes #145
> create_test_db: change path to a command line arg

- NEWS.md
This PR adds release notes for `v0.10.0`. I'll keep this **[WIP]** until the fix from #150 has landed.
Once this gets merged, I'll be sure to create an annotated tag using the following instruction:
```
git tag -a v0.10.0 -m "Tag v0.10.0" && git push upstream v0.10.0
```
> NEWS.md: add release notes for v0.10.0

- src/cmd/flux_account_update_fshare.cpp
- src/fairness/print_hierarchy/flux_account_shares.cpp
- t/expected/help_message.txt
- t/t1000-print-hierarchy.t
- t/t1006-update-fshare.t
Noted in #169, the optional path argument for several of the flux-accounting commands are inconsistent and should be unified.
---
This small PR changes the optional path arguments for the differing flux-accounting commands to be consistent across all the commands, `-p`.
I also snuck in a commit that removes a dangling comment in this PR as well, I hope that is okay. 
---
Fixes #169
> cmd: unify optional path argument

- README.md
- src/bindings/python/fluxacct/accounting/__init__.py.in
- src/cmd/flux-account.py
- src/cmd/flux_account_update_fshare.cpp
- src/fairness/print_hierarchy/flux_account_shares.cpp
- t/t1007-flux-account.t
Noted in #168, the default path for the FluxAccounting.db should be changed to `@X_LOCALSTATEDIR@/lib/flux/FluxAccounting.db`.
---
This PR changes the default path for the FluxAccounting.db to `@X_LOCALSTATEDIR@/lib/flux/FluxAccounting.db` since it is already set up to be owned by user flux. 
When building the project from source, one can use the following:
```shell
./autogen.sh && ./configure --localstatedir=/var/ && make -j && make check
```
to create a default DB location for `/var/lib/flux/`.
As long as the person or people administering the DB has permissions to this directory, then they should be able to interact with this DB, i.e adding banks and users, editing their information, and more. 
It also updates the default DB path for `flux account update-fshare` and adds a default DB …
> database: change default DB path, update README build instructions

- README.md
This PR adds the LLNL code release number to `README.md` to make flux-accounting more consistent with the other flux framework projects.
> doc: add LLNL code release number to README

- src/cmd/flux-account-priority-update.py
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/scripts/send_payload.py
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
- t/t1008-mf-priority-update.t
Mentioned in #133, currently the bulk update script that queries information from the flux-accounting database and sends it to the multi-factor priority plugin sends one JSON payload for every row in the database. This can be inefficient for a database with many users in it and could potentially cause problems if a user submits a job in the middle of a bulk update.
---
This is a **[WIP]** PR that improves the bulk update script by changing how the JSON payload is structured and sent to the plugin. Previously, for every user-bank row in the `association_table`, a payload was created containing all the necessary data and then sent to the plugin with every iteration. 
```
for every row in the association_table:
create one payload with result of SQLite query
send it to plugin with …
```
> flux-account-priority-update: change `bulk_update` method

- scripts/.pylintrc
- src/bindings/python/fluxacct/accounting/Makefile.am
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_create_db.py
- src/bindings/python/fluxacct/accounting/test/test_queue_subcommands.py
- src/cmd/flux-account.py
- t/t1007-flux-account.t
As discussed in #164, there is a need for being able to define and configure queue information within the flux-accounting database.
---
This is a [WIP] PR that I just wanted to post before the Thanksgiving break that adds such support within the DB. It adds a new table, `queue_table`, which holds just 4 columns - the name of the queue and a couple of required limits associated with each queue:
```
queue               tinytext        NOT NULL,
min_nodes_per_job   int(11),
max_nodes_per_job   int(11),
max_time_per_job    int(11),
PRIMARY KEY (queue)
```
_Note that the only column that is required when adding a new queue is the name; if not specified, all of the limit columns could just be empty, with no default values._
Support for interacting with this table from the command line with a …
> database: add queue_table, subcommands for interacting with queue_table

- NEWS.md
This PR adds release notes for flux-accounting `v0.12.0`. The other open PR #177 is not a blocker for this release. 
Once this gets merged, I'll be sure to create an annotated tag using the following instruction:
```
git tag -a v0.12.0 -m "Tag v0.12.0" && git push upstream v0.12.0
```
> NEWS.md: add release notes for `v0.12.0`

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- t/t1007-flux-account.t
As mentioned in #185, the `view-user` subcommand only prints the first result of a SQLite query fetching user information from the `association_table` even if the user belongs to multiple banks (and thus has multiple rows in the table).
---
This PR uses `cursor.fetchall()` to fetch all possible rows and iterate through them to print out all rows instead of just one. It also makes use of `.ljust()` to print out rows in a table-like format, similar to the output format of `pandas`, a data formatting module I removed from the project a while ago.
```console
$ flux account view-user fluxuser
creation_time   mod_time        deleted         username        userid          admin_level     bank            default_bank    shares          job_usage       fairshare       max_jobs        qos …
```
> `view-user`: add capability to view multiple rows

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- t/expected/flux_account/A_bank.expected
- t/expected/flux_account/D_bank.expected
- t/expected/flux_account/full_hierarchy.expected
- t/t1007-flux-account.t
Mentioned in #184, the `view-bank` command does not list children banks or users for a given bank. Moreover, the output when running this command can be sort of clunky and not pleasing. This PR looks to improve the command and add some more tests that make use of this command.
---
This is a small [WIP] PR looking to improve the command by changing the format of the output when viewing a bank within the flux-accounting database. Specifically, it looks to improve the output in the following ways:
- improve the output when viewing bank information to be formatted like a table, similar to the format of the `pandas` module before it was removed from flux-accounting:
```console
$ flux account view-bank A
bank_id         bank            parent_bank     shares          
2               A …
```
> view-bank: improve command, add more sharness tests

- scripts/.pylintrc
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/test/test_qos_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
- t/t1007-flux-account.t
While working on #176, a suggestion was made to keep the same arguments as the `add` subcommand instead of using the `--field` and `--new-value` optional args. The same improvement should probably also made to the `edit-user` subcommand. This will allow for multiple fields to be edited at the same time, allow for resets on optional fields, and will improve the overall usability of the command. 
---
This PR changes the `edit-user` subcommand to take the same positional and optional arguments as the `add-user` subcommand. This includes the following improvement to the command:
```console
$ flux account edit-user --username=user1234 --field="max_jobs" --new-value=1234
```
```console
$ flux account edit-user user1234 --max-jobs 100
```
It also allows for multiple values of a user/bank row to …
> `edit-user`: change positional and optional arguments to match `edit-qos` subcommand

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
- t/t1007-flux-account.t
While working on some of the improvements discussed to PR #177, I noticed a couple small miscellaneous bugs in the `view-user` and `add-user` subcommands while running them in my Docker container. The bugs are listed as follows:
- Mentioned in #191, the `admin_level` column still remains in the output of the `view-user` command. This results in incorrect output and should be removed. 
- Mentioned in #192, a user/bank row is added to the `association_table` with a user/bank combination (e.g. `user1234`, `bankA`), the row is removed, and then re-added, a `UNIQUE` constraint fails in the `job_usage_factor_table`.
---
This PR fixes both issues in these subcommands and adds small improvements to try and help mitigate similar bugs in the future. 
In the `view-user` command, I've changed the way …
> user_subcommands.py: fix miscellaneous bugs

- src/plugins/mf_priority.cpp
- src/test/docker/bionic/Dockerfile
- src/test/docker/centos8/Dockerfile
- t/t1001-mf-priority-basic.t
- t/t1005-max-jobs-limits.t
A little while ago it was brought up that the current enforcement of a max jobs limit used on our machines counts running jobs towards a user/bank row's max_jobs limit. Currently, the multi-factor priority plugin increments for all active jobs, not just running jobs.
---
This PR changes the way the plugin increments the `current_jobs` count for a user/bank row in the flux-accounting DB by incrementing the count when a job enters `job.state.priority` instead of `job.validate`. 
It also adds a new callback, `depend_cb ()`, which will tap into a job when it reaches `job.state.depend`. A check is performed in this callback to see if the user/bank already has `max_jobs` running; if it does, it adds a dependency on the recently submitted job and its job ID is pushed to the back of a list of …
> plugin: change max jobs limit enforcement

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/Makefile.am
- src/cmd/flux-account-pop-db.py
- t/Makefile.am
- t/expected/pop_db/db_hierarchy_base.expected
- t/expected/pop_db/db_hierarchy_new_users.expected
- t/t1009-pop-db.t
Populating the DB with many users and banks can be tedious, as currently there are really only two options:
- using the `add-bank` and `add-user` commands one at a time to add users and banks
- going into an interactive SQLite shell and using `INSERT` commands, one a time, to add both users and banks to the database
This can be cumbersome and slow, especially when the time comes to install flux-accounting on a system and we need to migrate a large set of users.
---
This PR adds a new command to flux-accounting, `flux account-pop-db`, which allows an admin to bulk populate a flux-accounting DB's `bank_table` and `association_table` using `.csv` files. The path to the file can be passed via the command line, and this command will iterate through the file and call `add_user ()` or `add_bank …
> cmd: add bulk DB populate command

- NEWS.md
- t/Makefile.am
This PR adds release notes for flux-accounting `v0.13.0`. ~~I'll keep this [WIP] until I've made a decision if any other fixes/new features should be merged before the end of the month.~~ 
Once this gets merged, I'll create an annotated tag using the following instruction:
```
git tag -a v0.13.0 -m "Tag v0.13.0" && git push upstream v0.13.0
```
> NEWS: add release notes for `v0.13.0`

- .mergify.yml
- src/test/docker/README.md
- src/test/docker/docker-run-checks.sh
- src/test/docker/el8/Dockerfile
- src/test/generate-matrix.py
The upstream flux-core `centos8` images has been renamed to `el8` to reflect the fact that CentOS is EOL.
---
This PR updates the `centos8` image name used in CI accordingly.
> ci: rename centos8 builder to "el"

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account.py
- src/plugins/mf_priority.cpp
- t/expected/flux_account/A_bank.expected
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
The `max_jobs` column is confusing and doesn't clearly represent what the column is for: limiting the number of _running_ jobs a user/bank combo can have running at any given time. When the `max_active_jobs` limit is added, it would be clearer to rename `max_jobs` to something more distinct.
---
This PR contains work split off from #201 that renames `max_jobs` to `max_running_jobs` throughout the flux-accounting project to more clearly describe the difference between a "running" jobs count and an "active" jobs count for a user/bank combo. It contains renaming changes to:
- the database
- the Python commands
- the multi-factor priority plugin
- the existing sharness tests
> database: rename max_jobs --> max_running_jobs

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
This is a small PR that removes the handwritten list of column names from the `print_user_rows()` and the `print_bank_rows()` helper functions and instead fetches the column names of the `association_table` and `bank_table` using `cursor.description`
so that the headers will automatically be updated every time a change is made to the tables.
> view-bank: remove manual list of column names

- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account.py
- src/plugins/mf_priority.cpp
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
The changes introduced in #177 left somewhat of a "bad behavior" loophole in the priority plugin when it comes to handling job submissions from a user/bank row. As a quick refresher, #177 introduced a change to the way the plugin kept track of a _running_ jobs for a user/bank row, so it only counts jobs that had entered the RUN state. So, for example, if a user/bank row had a `max_jobs` limit of 2, and they submitted 4 jobs at once, the first two jobs could enter the RUN state, but the other 2 would have dependencies added to them (thus, holding the jobs), until one of the first two jobs entered the INACTIVE state, which would remove the dependency on one of the held jobs and allow it to enter the RUN state.
However, there is currently no way to enforce the amount of _active_ jobs from a …
> plugin: add max_active_jobs per-user/bank limit

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/expected/job_usage/post_update1.expected
- t/expected/job_usage/post_update2.expected
- t/expected/job_usage/pre_update.expected
- t/scripts/create_job_archive_db.py
- t/t1010-update-usage.t
As described in #208, a `TypeError` occurs when not specifying a value for the `--priority-decay-half-life` optional argument in the `update-usage` command. This is because the argument has no default value, so if no value is specified, `None` is passed to the `calc_usage_factor()` function and it fails.
---
This PR fixes the `TypeError` in the `update-usage` command by adding a default value for the `--priority-decay-half-life` optional argument, 1, which matches the default value in the flux-accounting database. 
It also adds a new sharness test file, `t1010-update-usage.t`, which creates both a sample flux-accounting DB and job-archive DB, populated with a set of fake job records. It then runs the `update-usage` command twice, one using the default value and another specifying a value …
> job-archive interface: update optional `--priority-decay-half-life` argument

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
- src/cmd/flux-account.py
- src/test/docker/bionic/Dockerfile
- t/Makefile.am
- t/scripts/create_job_archive_db.py
- t/scripts/query.py
- t/t1011-job-archive-interface.t
As noted in #210, the `count_ranks()` helper function incorrectly parses the `ranks` column when there is a range of ranks. This leads to a `ValueError` when counting the number of nodes used in a job.
---
This PR removes the `count_ranks()` helper function and instead imports the `ResourceSet` class from flux-core, which can then extract `nnodes` from a job's `R`. Note that in both the unit test file for **job_archive_interface.py** and the sharness test file **t1010-update-usage.t**, the calculated usage values checked in the tests remain the same for all users, which ensures consistency after the change to the way the job-archive interface extracted the `nnodes` values from job records.
It also contains a small improvement to the `update-usage` command to add a special option to the …
> job-archive interface: remove `count_ranks()` helper function, import ResourceSet class

- NEWS.md
This PR adds release notes for flux-accounting `v0.14.0`.
Once this gets merged, I'll create an annotated tag using the following instruction:
```
git tag -a v0.14.0 -m "Tag v0.14.0" && git push upstream v0.14.0
```
> NEWS: add release notes for `v0.14.0`

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
- t/scripts/create_job_archive_db.py
- t/t1011-job-archive-interface.t
As noted in #218, the job usage calculation function `calc_usage_factor()` calculates the same usage value for a user's default bank row and all secondary bank rows in the `association_table`. This results in the same usage value for all banks which the user belongs to, which is incorrect since jobs should only count towards usage for the bank they submitted jobs under.
---
This PR looks to improve the job-usage calculation for a user/bank row by only counting jobs that are submitted under the intended bank. 
The query used in the `update_job_usage()` function (the function responsible for iterating through all user/bank rows in the `association_table`) is  changed to include the `default_bank` column to help determine whether jobs should be counted towards a user's default bank or one of …
> job-archive interface: improve bank-specific usage calculation

- README.md
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/test/test_create_db.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-pop-db.py
- t/t1009-pop-db.t
Not a super high priority item, just some random fixes throughout the project I wanted to get posted.
* The `pop-db` command is updated to include the new `max_active_jobs` and `max_running_jobs` columns from the `association_table`. The outdated `QoS` column is replaced with `Queues`.
* The 'deleted' column in the `association_table` won't be able to actually represent a deleted row from the table
since the row is actually removed from the table itself, so just remove the column from the table.
* Some of the lines in `README.md` go way over ~~60~~ 80 characters, so break up those long lines into multiple lines.
> flux-accounting: miscellaneous fixes, improvements

- src/cmd/flux-account.py
- t/t1007-flux-account.t
In an offline conversation with @ryanday36, he reported that when trying to edit a value in a user/bank row in the `association_table`, a `Queue does not exist in the queue_table` message would pop up and prevent the row from being successfully edited. 
```console
[root@machine:~]# flux account edit-user --max-active-jobs 999 user1
Queue specified does not exist in queue_table
```
This is because the "queues" optional argument in the `edit-user` command has a default value of `""` instead of `None`, which means when someone tries to edit a field for a user, the `validate_queues()` function will be triggered because the `edit_user()` function thinks that a queue of name `""` has been passed, which is incorrect.
---
This PR changes the default value of queues to `None` so that when a field …
> `edit-user`: change default value of "queues" optional argument

- .github/workflows/main.yml
A recent release of `click` breaks the version of `black` used in flux-accounting's GitHub Actions as noted by this issue thread:
https://github.com/psf/black/issues/2964
---
Pin the `click` package to 8.0.2 to prevent the break (reference: https://stackoverflow.com/questions/71673404)
I think since this PR modifies GitHub actions, it might need a manual merge?
> ci: pin click package to 8.0.2

- Makefile.am
- etc/01-flux-account-priority-update
_I'm posting this as an early work-in-progress, as I'm not sure I have everything required to add an `rc1` script to flux-accounting just yet, but I figured I would post it now._
As noted in #221, when the multi-factor priority plugin is re-loaded after a `systemctl restart flux`, `flux account-priority-update` has to be run again in order to re-populate the plugin with the user/bank information from the flux-accounting database. A suggestion was made to see if the data sent to the plugin could be initiated automatically so that the `flux account-priority-update` command does not have to be manually run again.
---
This PR adds an `etc/` directory to flux-accounting and adds an `rc1` script named `01-flux-account-priority-update`, which will attempt to populate a loaded multi-factor …
> flux-accounting: add `etc/` directory, `rc1` script

- src/cmd/flux-account-priority-update.py
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1001-mf-priority-basic.t
- t/t1012-mf-priority-load.t
The plugin currently rejects jobs in `job.validate` when it cannot find the userid of the user/bank combo submitting the job in its internal map data structure. A suggestion was made in #222 to change this behavior to instead hold the job until the correct information was received. Then, upon a data update via `flux account-priority-update`, the plugin could reprioritize all jobs using `flux_jobtap_reprioritize_all ()` with the newly pushed information and release any jobs still waiting on user/bank information.
---
This PR looks to add support for holding jobs when the user/bank information cannot be found in the plugin's internal map. It removes the rejection in `job.validate` and instead creates a special temporary entry in the users map and sets a special `max_run_jobs` value to let …
> plugin: allow user/bank information to be loaded late, add job.new callback

- NEWS.md
End of the month is here, so here are some release notes for the `v0.15.0` release notes for flux-accounting. ~~I don't think I expect any of the current standing PR's to be landed before `v0.15.0` is released, but I'll leave it [WIP] just in case any last minute quick fixes need to be pushed up by today.~~ 
This release contains a couple of fixes reported by @ryanday36 in his interactive testing that deal with job usage calculation and the `edit-user` command.
> NEWS.md: add release notes for `v0.15.0`

- src/cmd/flux-account-priority-update.py
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
- t/t1008-mf-priority-update.t
- t/t1012-mf-priority-load.t
- t/t1013-mf-priority-queues.t
The cleanup work described in #204 has now been completed with the merge of #205 and now allows for the start of integrating the use of queues into the priority plugin. I think there are two prongs to adding queue support into the plugin:
1) the use of a queue's associated priority to further increase or decrease the priority of a job submitted from a user/bank (which is the focus of this PR), and
2) the enforcement of per-job limits using a queue's associated limits (the work of a future PR)
---
This PR looks to integrate queue information into the priority calculation of a job in the multi-factor priority plugin. At a high level, the goal is to use queue information to further calculate a job priority using the information from the `queue_table` in the flux-accounting database, which …
> plugin: add queue priority to priority calculation, plugin

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1014-mf-priority-dne.t
Mentioned in #231, the `DNE` entry for a user/bank combo gets deleted when an active job under that user/bank transitions to `job.state.inactive`, but any other active job under the same user/bank still referencing that deleted `DNE` entry will cause a seg fault and the plugin to break.
---
This PR removes the deletion of the DNE entry from the users map for a user/bank entry in the internal `users` map. 
I also added a sharness test (`t1014-mf-priority-dne.t`) that attempts to imitate the steps outlined in the reproducer shown in #231, but it might be worth to try this branch against that reproducer itself to make sure the same error does not occur.
> plugin: fix memory corruption due to use-after-free of "DNE" bank entry

- NEWS.md
_Nearing the end of the month, so I figured I'd get this up now to have it ready. :-)_
This PR adds release notes for flux-accounting `v0.16.0`. ~~Leaving [WIP] for now to see if I can get #230 (or any other tiny fixes/features) landed before I release.~~ 
Once this gets merged, I'll create an annotated tag using the following instruction:
```
git tag -a v0.16.0 -m "Tag v0.16.0" && git push upstream v0.16.0
```
> NEWS: add release notes for v0.16.0

- src/plugins/mf_priority.cpp
- t/t1013-mf-priority-queues.t
The multi-queue design is not fully designed and implemented throughout the various Flux components yet, but the plugin requires that a `default` queue exist in order to submit jobs with the plugin loaded.
---
Disable the validation of queues as well as its use of an associated integer priority with queues passed in from the flux-accounting DB so that a `default` queue does not need to be present in order for users to submit jobs with the multi-factor priority plugin loaded. I just commented out the sections of code that perform this validation, but if we think it would be cleaner to just remove the code altogether, I am OK with that as well.
Disable the tests that check for queue validation error messages and that check for specific job priorities affected by queue priorities. I just …
> plugin: disable queue validation, `default` queue requirement

- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-pop-db.py
- src/cmd/flux-account.py
- t/t1009-pop-db.t
Described in #121, there is a need for supporting a `max_nodes` limit on user/bank associations. More specifically, this limit will enforce a maximum number of nodes a user/bank association can have across all of their running jobs at any given time.
---
This is a small PR that simply adds the `max_nodes` column to the `association_table` in the flux-accounting database. It also adds `max_nodes` as an optional argument to the `add-user` and `edit-user` commands.
> association_table: add `max_nodes` column

- .github/workflows/main.yml
This PR looks to add CI steps for automatically creating and deploying a flux-accounting release when a new tag is created. I just looked at flux-core's `main.yml` for the auto-deploy steps, but am not sure if I copied everything I needed to. Let me know if I missed anything.
Fixes #154
> github actions: add auto-deploy steps for a new flux-accounting tag

- src/plugins/mf_priority.cpp
- t/t1001-mf-priority-basic.t
The multi-factor priority plugin currently rejects jobs from a user who has a fairshare value of exactly 0.0. As discussed in #141, the plugin should instead assign the lowest job priority for the job submitted.
---
This PR removes the job rejection from the plugin when a user has a fairshare value lower than 0.00000 and instead returns `FLUX_JOB_PRIORITY_MIN` when calculating the priority of a job. 
When a fairshare update occurs and updated information is sent to the plugin and jobs are reprioritized, there is potential to update the existing priority for a job and raise its priority to higher than `FLUX_JOB_PRIORITY_MIN`.
The test that checks for a successful job rejection in `t1001-mf-priority-basic.t` is also updated to instead check that the assigned priority is …
> plugin: change behavior for users who have extremely low/zero fairshare

- src/Makefile.am
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-export-db.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1016-export-db.t
As mentioned in #215, there will be a need for supporting the ability to update the flux-accounting database when a new version of the database is released so that the existing DB does not have to be completely re-created and have all values re-inserted. This will be especially important when new columns are added to an already existing table or a new table is added.
---
This PR adds a new command to flux-accounting: `export-db`, which allows an admin to export information from the `association_table` and `bank_table` in the flux-accounting DB into two `.csv` files. This can be used to then import user and bank information into a new flux-accounting DB. Custom paths and filenames can be specified for these two files, or, if left default, will just create the two `.csv` files in the …
> flux-account: add DB export command

- src/bindings/python/fluxacct/accounting/__init__.py.in
- src/bindings/python/fluxacct/accounting/create_db.py
- src/cmd/flux-account-export-db.py
- src/cmd/flux-account-pop-db.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account-update-db.py
- src/cmd/flux-account.py
- t/t1017-update-db.t
This is a small PR that adds a schema version number to the flux-accounting database. This integer version number represents the version of the most current DB schema and will only change when the schema of the DB changes from one version to the next. It is defined with the other `fluxacct` package variables, `db_dir` and `db_path` in the project's `__init__.py.in` file.
A check has also been added to the flux accounting commands that looks at the version number of the database the command is trying to connect to. If the version number is less than the version number defined in `__init__.py.in`, a message will be output saying that the DB is out of date and should be updated with `flux account-update-db`. This command will now do two additional things:
1) if the DB is out of date, it will …
> flux-accounting: add DB schema version to flux-accounting DB

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
This is a minor cleanup PR of the bank commands and unit tests. It cleans up the `add_bank()` function by moving some validation to a helper function and changes a couple of the exceptions that get raised in the `validate_parent_bank()` helper function and `edit_bank()` function from a general Python exception to a `ValueError`.
It also looks to clean up some of the test names and descriptions of the unit tests for the bank functions, as some of them are poorly worded (thanks to me! 😆) and could use some improvement.
> python: improve bank command bindings, test names and descriptions

- configure.ac
- t/sharness.d/flux-sharness.sh
- t/t1013-mf-priority-queues.t
Problem: flux-accounting's `t1013-mf-priority-queues.t` test was failing in CI for flux-framework/flux-core#4627.
The job manager is made more picky about the queue config by that PR.  It's no longer possible to submit a job for a queue that is not in a `[queues]` configuration,  as the job manager now rejects it at submission.
There was also a failing test which checked that flux-accounting assigned a default queue if one was configured.  This is now handled at ingest by the "frobnicator" so flux-accounting should not need to assign defaults.  I removed the test (and another related one that was already commented out).  I'll open another issue to track changes that might be needed in flux-accounting for these queue changes.
There are a couple of minor cleanups here as well.
> testsuite: adjust queue tests for flux-core changes

- src/plugins/mf_priority.cpp
- t/t1013-mf-priority-queues.t
- t/t1018-mf-priority-disable-entry.t
The multi-factor priority plugin currently rejects jobs which submit a queue that the plugin does
not know about and when the plugin does not have a configured "default" queue. The changes proposed in https://github.com/flux-framework/flux-core/pull/4627
enable the flux-core job-manager to be more aware of queues and instill queue validation on its own.
As a result of this, the plugin should relax some of its current enforcements
on queue validation.
---
This PR relaxes some of its queue validation in 2 cases when an association submits a job:
- when it does not recognize the queue specified
- when no queue is specified
In both of these cases, the plugin assign's a default factor of 0 to the overall job priority calculation. It changes a couple of the preprocessor directives the plugin …
> plugin: disable queue validation on an unknown queue, no configured "default" queue

- src/plugins/mf_priority.cpp
- t/t1014-mf-priority-dne.t
As noted in #283, when the multi-factor priority plugin encounters a job for which it has no user/bank info, it allows one job to be submitted, but not subsequently submitted jobs. This is because it **does not** set the `active` field (which has a default value of 0) for the "DNE" entry it creates for the user/bank to during the first job submission, which means that any following submitted job would be met with a rejection message explaining that the user is disabled from the database:
```
[Errno 22] user/bank entry has been disabled from flux-accounting DB
```
---
This PR changes some of the default values of the "DNE" entry created for a user/bank when they submit jobs while their information is not loaded from the flux-accounting database. It sets `active` to 1 to prevent them from …
> plugin: change default values of "DNE" entry to allow multiple jobs to be submitted

- src/plugins/Makefile.am
As noted in #284, mf_priority.so is installed to `$libdir`, but the job manager looks for it in `$libdir/flux/job-manager/plugins`.
---
This PR takes the suggestion from @garlick (and @jameshcorbett) in #284 and changes the install location of the plugin in its Makefile.am. After this PR lands, the following lines should be removed from flux-accounting's `.spec` file:
```
mkdir -p ${RPM_BUILD_ROOT}%{_libdir}/flux/job-manager/plugins
mv ${RPM_BUILD_ROOT}%{_libdir}/mf_priority.so ${RPM_BUILD_ROOT}%{_libdir}/flux/job-manager/plugins/
```
Fixes #284
> plugin: change install location

- NEWS.md
This PR adds release notes for flux-accounting `v0.20.0`. The other outstanding PR's in this repository should not be critical to land for this release as they are minor cleanups/fixes, or they still warrant some further thinking or discussion. :-)
Once this lands, I'll create an annotated tag with:
```
git tag -a v0.20.0 -m "Tag v0.20.0" && git push upstream v0.20.0
```
> NEWS: add release notes for v0.20.0

- src/cmd/flux-account-update-db.py
- t/t1017-update-db.t
As noted in #285, the `update-db` command fails during an automatic update because it is trying to create a temporary flux-accounting database in the broker's current working directory, which is `/`. The `update-db` command's behavior creates this temporary database in the current working directory, which causes problems if the directory does not have the correct permissions.
---
This PR uses the `tempfile` module to create a temporary directory inside `/tmp/` to store the temporary flux-accounting DB that gets created during an update. After the update is completed, the directory is cleaned up and removed. This should prevent the temporary database from attempting to be created wherever the command is running from, which might not have the necessary permissions.
Fixes #285
> `update-db`: use tempfile module for temporary flux-accounting DB during upgrade

- NEWS.md
This PR adds release notes for `v0.20.1`, which contains fixes for the errors described in #285. 
Once this PR lands, I'll create an annotated tag with the following command:
```
git tag -a v0.20.1 -m "Tag v0.20.1" && git push upstream v0.20.1
```
> NEWS: add release notes for v0.20.1

- src/bindings/python/fluxacct/accounting/test/test_project_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- t/t1007-flux-account.t
As noted in #276, the `add-user` command does not validate the bank specified when adding a user to the flux-accounting database. So, a user can be added to a bank that does not exist in the `bank_table`.
---
This is a small PR that adds a validation helper function that looks at the bank being specified when adding a user. If the bank does not exist in the `bank_table`, it raises a ValueError with a message saying that the bank does not exist in the database, and does not add the user.
Both a unit test and sharness test are added to ensure that a non-existent bank in fact does raise a `ValueError` and prevents a user from being added to the flux-accounting database.
> add-user: add bank validation

- .github/workflows/main.yml
Using ubuntu-latest in the python-lint causes the check to fail with an error message saying that Python `3.6` cannot be found.
---
This PR just switches the version of Ubuntu to match flux-core's Ubuntu version in their `python-lint` check: `20.04`.
> github: change Ubuntu version for python-lint check

- t/t1013-mf-priority-queues.t
Problem: In t1013-mf-priority-queues.t, newly created job queues
are assumed to be stopped due to a call to `flux queue stop` earlier
in the tests.  A queue defaulting to stopped cannot be assumed.
Add an additional call to flux queue stop after the job queues
are created.
See investigation in https://github.com/flux-framework/flux-core/pull/4776
> testsuite: do not assume queues default to stopped

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/expected/print_hierarchy/after_parent_bank_change.expected
- t/expected/print_hierarchy/before_parent_bank_change.expected
- t/t1000-print-hierarchy.t
As described in #298, the parent bank of a bank cannot be edited, so in order to move a bank and its users, it must be deleted and re-created under the new parent bank. The `edit-bank` command should be extended to allow the parent bank to be edited.
---
This is a small PR that extends the `edit-bank` command to allow edits of a parent bank. This would remove the need to delete and then re-add a bank and all of its users under the new parent bank. 
A couple of unit test and sharness tests are also added to make sure it works as expected. The unit tests make sure that a bank's parent bank can be changed, and trying to edit a bank's parent bank to one that does not exist raises a `ValueError`. The sharness test adds a bank and some users before editing the parent bank to confirm that the …
> edit-bank: add ability to edit parent bank

- t/rc/rc1-job
- t/t1013-mf-priority-queues.t
Problem: flux-core PR 4776 added the ability for queues to be individually started and stopped.  As an update, starting/stopping all queues with the `flux queue` command now requires the --all option to be specified, otherwise a warning is output.
To avoid the warning, update all callers to specify --all when multiple queues are started or stopped.
This is similar to https://github.com/flux-framework/flux-sched/pull/992
***This should not be merged until https://github.com/flux-framework/flux-core/pull/4776 is merged***
> testsuite: stop all queues with --all option

- NEWS.md
After the added feature in #299 and the fixes proposed by @chu11 in #302 and #303, I think it's definitely worth tagging and releasing a new version of flux-accounting. This PR adds release notes for `v0.21.0`.
This PR should not be merged until after #303 has been merged.
Once this lands, I'll create an annotated tag with the following command:
```console
git tag -a v0.21.0 -m "Tag v0.21.0" && git push upstream v0.21.0
```
> NEWS: add release notes for `v0.21.0`

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account.py
- t/expected/flux_account/A_bank.expected
- t/expected/flux_account/deleted_bank.expected
- t/expected/flux_account/root_bank.expected
- t/t1007-flux-account.t
- t/t1011-job-archive-interface.t
The Python functions in the `Accounting` class directly emit output to `STDOUT` instead of `return`-ing information to the caller of the function. To prepare for the transition to using a systemd-managed service that accepts an RPC to call the Python functions, this behavior should be changed to `return` information to the caller of the function.
---
This PR redesigns a number of the functions in the `Accounting` class to `return` any information that would otherwise be emitted to `STDOUT` using `print()` statements. The front-end Python script that calls these functions has also been adjusted to assign the returned value to a variable, where it is then `print()`-ed out.
A couple of the existing sharness tests required slight changes to expected output as a result of the redesign …
> python: redesign functions in `Accounting` class

- src/Makefile.am
- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_queue_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1000-print-hierarchy.t
- t/t1007-flux-account.t
- t/t1008-mf-priority-update.t
- t/t1009-pop-db.t
- t/t1010-update-usage.t
- t/t1011-job-archive-interface.t
- t/t1013-mf-priority-queues.t
- t/t1016-export-db.t
- t/t1017-update-db.t
- t/t1018-mf-priority-disable-entry.t
- t/t1019-mf-priority-info-fetch.t
`flux account` commands can currently only be executed on the management node of a cluster (where the flux-accounting DB is installed). So, users/admins who want to run simple `flux account` commands to see user or bank info cannot run these commands from other nodes on a cluster. There is a need to improve this and enable commands to interface with the DB "remotely."
---
This is an early [WIP] PR that introduces a new service to flux-accounting that can be managed by `systemd` and is designed to run on the rank 0 broker of a Flux system instance. This service, `flux-account-service.py`, is installed to `${prefix}/libexec/flux/cmd` and can be started _after_ the creation of a flux-accounting database:
```console
$ flux account-service -p path/to/db &
[1] 1234
```
If no path is specified …
> python: introduce new service for `flux account` commands

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1011-job-archive-interface.t
The call to `output_job_records()` in **flux-account-service.py** currently fails due to a mismatch in arguments to the function.
```console
$ sudo flux account view-job-records
Traceback (most recent call last):
File "/usr/libexec/flux/cmd/flux-account.py", line 679, in <module>
main()
File "/usr/libexec/flux/cmd/flux-account.py", line 675, in main
select_accounting_function(args, output_file, parser)
File "/usr/libexec/flux/cmd/flux-account.py", line 554, in select_accounting_function
return_val = flux.Flux().rpc("accounting.view_job_records", data).get()
File "/usr/lib64/flux/python3.6/flux/rpc.py", line 77, in get
resp_str = self.get_str()
File "/usr/lib64/flux/python3.6/flux/util.py", line 90, in func_wrapper
retval = func(future, *args, **kwargs)
File …
```
> view-job-records: fix arguments passed in via `flux-account-service.py`

- NEWS.md
This PR adds release notes for `v0.22.0` to be accompanied with flux-accounting's upcoming March release. Leaving this as [WIP] to see if we can land #316 beforehand.
> NEWS: add release notes for `v0.22.0`

- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1007-flux-account.t
As reported in #318, the "userid" field for a user is not editable in the `association_table`, so when a user is created in the DB before they are in the passwd file, they get a default UID of 65534 with no way to edit it unless they go into a SQLite shell and manually edit the column themselves.
---
This PR adds "userid" as an editable field in the `edit-user` command. It also adds a unit test and a sharness test that confirms that the userid can be edited.
Fixes #318
> edit-user: make "userid" an editable field

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_project_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_queue_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- t/t1007-flux-account.t
As mentioned in #309 and #310, the `view-*` commands for flux-accounting still "succeed" even when the item being searched cannot be found in the flux-accounting DB. It's current behavior is just to return a string saying "Item not found in *_table." This behavior should be changed to instead raise an exception.
---
This PR changes the functions called by the various `view-*` commands to instead raise a `ValueError` when an item cannot be found in the flux-accounting database. The error is caught by the flux-accounting service and a message is sent saying, for example:
```console
$ flux account view-user foo
error in view-user: User not found in association_table
```
The respective unit and sharness tests are also slightly changed to account for this new raised exception when a user …
> `view-*` commands: raise `ValueError` when item cannot be found in flux-accounting DB

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/expected/flux_account/D_bank.expected
- t/expected/flux_account/full_hierarchy.expected
- t/t1007-flux-account.t
As reported in #321, the `-t` option no longer exists in flux-accounting. That's because it was removed in #307, but is still used in scripts, so it needs to be re-added.
---
This PR re-adds the `-t` option to the `view-bank` command, which returns a hierarchy tree containing all sub banks and users under the bank passed into the `view-bank` command. The tests that checked for expected output of the `view-bank` command are also re-added to `t1007-flux-account.t`, slightly adjusted in format because of the new way the Python bindings return information (instead of directly printing to `STDOUT`), but still contain the same information.
Fixes #321
> view-bank: re-add `-t` option to command

- NEWS.md
This PR adds release notes for flux-accounting `v0.22.1`, which includes a number of fixes brought on by recent testing of `v0.22.0`. Once this lands, I'll create a new annotated tag with the following command:
```
git tag -a v0.22.1 -m "Tag v0.22.1" && git push upstream v0.22.1
```
> NEWS: add release notes for `v0.22.1`

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1020-mf-priority-issue262.t
As noted in #262, the plugin currently incorrectly handles calculating running job counts for associations (user/bank combos). It increments the running job count in `job.state.priority`, which could result in a double increment if the job re-enters PRIORITY state after a reprioritization of jobs via `flux account-priority-update`.
The plugin also incorrectly handles decrementing running and active job counts when a job enters `job.state.inactive`. Even if a job did not run, the plugin still decrements the association's current running jobs count and looks to release any held jobs from a max running jobs dependency, which could result in incorrect running job counts.
---
This PR looks to rework the way the plugin increments **and** decrements running and active job counts for an …
> plugin: rework increment/decrement of running job counts

- NEWS.md
This PR adds release notes for flux-accounting `v0.22.2`, which includes fixes for issues reported in #262. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.22.2 -m "Tag v0.22.2" && git push upstream v0.22.2
```
> NEWS: add release notes for v0.22.2

- src/bindings/python/fluxacct/accounting/test/test_project_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- t/t1007-flux-account.t
The functions called by all of the `user-*` commands handle any exceptions raised during execution and just return a string containing the error message. This behavior should be changed to be more Pythonic and raise errors to the caller of the function.
As noted in #313, this behavior currently exists in all of the Python bindings, but instead of creating one large PR that changes the behavior for all of the bindings at once, it might be a little cleaner to post subsequent, smaller PRs that change the bindings one file at a time. This one starts with `user_subcommands.py`.
---
This PR changes the behavior of a number of the functions in `user_subcommands.py` to raise any error to the caller of the function with a clear message explaining what the error is. For `sqlite3.OperationalError`, …
> `user-*` commands: change error handling to raise error to caller

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
- src/cmd/flux-account-service.py
- t/t1007-flux-account.t
- t/t1017-update-db.t
This PR continues the work brought on by #327 and changes the behavior of a number of the functions in `bank_subcommands.py` to raise any error to the caller of the function with a clear message explaining what the error is.
New exception handlers are added to the flux-accounting service to handle a raised error and print out a formatted message describing the error that occurred. 
The unit/sharness tests for the `bank-*` commands are also adjusted to account for the new behavior of the commands that raise an exception on certain errors, and a couple new unit and sharness tests are also added to further check for expected raised errors.
> `bank-*` commands: change error handling to raise error to caller

- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_project_subcommands.py
- src/bindings/python/fluxacct/accounting/test/test_queue_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- t/t1007-flux-account.t
This PR completes the work brought on by https://github.com/flux-framework/flux-accounting/pull/327 and changes the behavior of a number of the functions in `queue_subcommands.py` and `project_subcommands.py` to raise any error to the caller of the function with a clear message explaining what the error is.
New exception handlers are added to the flux-accounting service to handle a raised error and print out a formatted message describing the error that occurred.
The unit/sharness tests for the `queue-*` and `*-project` commands are also adjusted to account for the new behavior of the commands that raise an exception on certain errors, and a couple new unit and sharness tests are also added to further check for expected raised errors.
> `*-queue`/`*-project` commands: change error handling to raise error to caller

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1021-mf-priority-issue332.t
As reported in #332 and #333, there are a couple of issues with how the plugin handles unpacking queues on a flux-accounting update.
1) If a user who has been added to a queue via `flux account edit-user --queue=_queue_name user_name_` is removed from that queue with `flux account edit-user --queue= _user_name_`, their access to the queue persists after running an `account-priority-update`.
2) If a queue is deleted with `flux account delete-queue ...`, and then `flux account-priority-update` is run, users who were not given access to it continue to be unable to submit to it.
This is because both the `queues` field for a user entry in the plugin and the `queues` map itself are not cleared before an update, so if queues are removed for a user or if queues are removed in the `queues_table` …
> plugin: clear queues on flux-accounting DB update

- NEWS.md
This PR adds release notes for flux-accounting `v0.23.0`. It includes the changes to error handling in the Python bindings and the bug fix for updated queue lists in the multi-factor priority plugin. Once this is merged, I'll create an annotated tag with the following command:
```
git tag -a v0.23.0 -m "Tag v0.23.0" && git push upstream v0.23.0
```
> NEWS: add release notes for `v0.23.0`

- etc/flux-accounting.service.in
Flux can be restarted by systemd because it is mentioned as a `Requires` by flux-accounting, which has `Restart=Always`. We don't want Flux to be auto-restarted when the admins don't expect it.
---
This PR changes `Requires=flux.service` to `BindTo=flux.service`. This should allow things to behave more as expected, i.e if Flux is shut down, then flux-accounting is also, and similarly when Flux is started, the flux-accounting service is started.
Fixes #337
> flux-accounting service: change `Requires` to `BindTo`

- NEWS.md
This PR adds release notes for flux-accounting `v0.23.1`. It includes the bug fix to the flux-accounting systemd unit file to prevent Flux from being auto-restarted. Once this is merged, I'll create an annotated tag with the following command:
```
git tag -a v0.23.1 -m "Tag v0.23.1" && git push upstream v0.23.1
```
> NEWS: add release notes for `v0.23.1`

- etc/flux-accounting.service.in
The flux-accounting systemd unit file uses `BindTo` instead of `BindsTo`. @jameshcorbett  pointed out that `BindsTo` is the correct variable to use according to: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#BindsTo=
---
This PR changes `BindTo` to `BindsTo` in the flux-accounting systemd unit file. Note that the flux-accounting service was still able to be started on fluke according to @grondo, so a new release doesn't seem to be necessary at the moment.
> flux-accounting service: change `BindTo` to `BindsTo`

- src/cmd/flux-account-update-db.py
The `add_stmt` used to add tables to an old version of a flux-accounting DB breaks when a table does not have a primary key. The generated statement used to update the table ends in a comma with nothing else after it, which results in a `sqlite3.OperationalError`.
---
This PR changes the construction of the `add_stmt` to only add a comma if the column is not the last one in the table. It moves the outer parentheses and semi-colon to the very end of the `add_stmt` construction instead of inside the for-loop where a PRIMARY KEY is generated. It also includes some minor cleanup that removes some unused variables from a couple function definitions.
> `update-db`: fix statement when updating a table with no primary key

- src/cmd/flux-account-service.py
- t/t1007-flux-account.t
All of the message handlers in the flux-accounting service are only available to the instance owner, but some of them should be open to all users. Commands that simply read from the flux-accounting DB, like `view-user`, `view-bank`, etc. should be able to be run by any user in on the machine, while others that write to the DB, like `add-user`, `add-bank`, should only be able to be run by a privileged group of administrators.
---
This PR breaks up the `endpoints` list into two smaller lists, one that is "general" and can be run by any user, and one that is "privileged" and is only available to the instance owner. Specifically, from the "general" list, the watchers set a rolemask to `FLUX_ROLE_USER` when creating the watcher.
A couple of tests are also added to `t1007-flux-account.t` that …
> flux-accounting service: make certain commands accessible to all users

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1007-flux-account.t
Mentioned in #340, the output of the `view-user` command is quite ugly because of how many columns there are in the `association_table`. Often times the output wraps around the terminal which makes it hard to look at.
---
This PR changes the format of the output of `view-user` to print user information vertically instead of horizontally. This way the output of the command looks cleaner and easier to look at.
It also slightly changes the tests that look for output of this command to use `grep -w` instead of calling `grep` multiple times. Passing the `-w` flag allows `grep` to look for multiple strings in the output, which was the original intention of the tests.
@ryanday36 let me know if this new output of the `view-user` command looks okay to you, or if you had another format in mind, I'd …
> `view-user`: improve formatting of output of command

- t/scripts/submit_as.py
- t/t1001-mf-priority-basic.t
- t/t1011-job-archive-interface.t
- t/t1012-mf-priority-load.t
- t/t1014-mf-priority-dne.t
- t/t1018-mf-priority-disable-entry.t
`flux mini CMD` is deprecated in favor of `flux CMD`.
---
This PR replaces the old usage in the test suite.
> test: replace "flux mini" usage

- NEWS.md
This PR adds release notes for flux-accounting `v0.24.0`. Leaving as [WIP] for now in case any last minute changes are added before we want to release (release date can also be changed in the `NEWS` document). Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.24.0 -m "Tag v0.24.0" && git push upstream v0.24.0
```
> NEWS: add release notes for `v0.24.0`

- NEWS.md
This PR adds release notes for flux-accounting `v0.25.0`. This version includes the improvements to the multi-factor priority plugin brought on by #347. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.25.0 -m "Tag v0.25.0" && git push upstream v0.25.0
```
> NEWS: add release notes for v0.25.0

- t/Makefile.am
- t/python/t1000-example.py
- t/python/tap/.gitignore
- t/python/tap/.travis.yml
- t/python/tap/COPYING
- t/python/tap/README.md
- t/python/tap/example/example.py
- t/python/tap/pycotap/__init__.py
- t/python/tap/setup.py
- t/python/tap/test/test.py
flux-accounting doesn't have a directory to run Python tests in `t/`. Having one would be useful to run unit tests on some of the front-end Python scripts.
---
This PR copies the `t/python/` directory from flux-core and adds it to flux-accounting's `t/` directory. It also adds an example unit test to the directory to make sure it works.
> t: add a Python test directory to `t/`

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- t/Makefile.am
- t/expected/flux_account/A_bank.expected
- t/expected/flux_account/D_bank.expected
- t/expected/flux_account/F_bank_tree.expected
- t/expected/flux_account/F_bank_users.expected
- t/expected/flux_account/full_hierarchy.expected
- t/expected/flux_account/root_bank.expected
- t/t1007-flux-account.t
There is no way to see an overarching view of a flux-accounting hierarchy without running `flux account-shares`, which includes job usage values for banks and users all in one place. It would be nice if you could see this view with a Python command.
---
This PR edits the `-t` option of the `view-bank` command to more closely match the output of the `flux account-shares` command in Python, which includes job usage values for banks and fair share values for users all in one place. The new format of the `-t` option is the following:
```console
$ flux account view-bank -t root
bank_id        bank           active         parent_bank    shares         job_usage      
1              root           1                             1              0.0            
Bank …
```
> `view-bank`: improve `-t` option

- NEWS.md
This PR adds release notes for flux-accounting `v0.26.0`. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.26.0 -m "Tag v0.26.0" && git push upstream v0.26.0
```
Leaving this as [WIP] until #361 lands and/or there are other last minute fixes needed before a release. 🙂
> NEWS: add release notes for v0.26.0

- src/fairness/account/account.cpp
- src/fairness/reader/data_reader_base.cpp
- src/fairness/reader/data_reader_db.cpp
- src/fairness/reader/test/data_reader_db_test01.cpp
- src/fairness/weighted_tree/test/weighted_tree_load.cpp
- src/fairness/weighted_tree/test/weighted_tree_test01.cpp
- src/fairness/weighted_tree/weighted_tree.cpp
- src/fairness/weighted_tree/weighted_walk.cpp
- src/fairness/writer/data_writer_base.cpp
- src/fairness/writer/data_writer_db.cpp
- src/fairness/writer/data_writer_stdout.cpp
- src/fairness/writer/test/data_writer_db_test01.cpp
- src/plugins/mf_priority.cpp
As mentioned in #365, `config.h` is not included in many of the `.cpp` source modules. Sometimes configure defines macros that affect how other header files are interpreted.
---
This PR adds `config.h` include statements in the `.cpp` source files that do not already have them.
mf_priority.cpp already had this include, but it also had an `extern "C"` preface, which is not needed, so this PR also drops that.
> .cpp: add config.h include to source code

- .mergify.yml
- src/test/docker/README.md
- src/test/docker/jammy/Dockerfile
- src/test/generate-matrix.py
Like flux-sched, flux-accounting also uses a `bionic` container as a part of its CI checks, but the Ubuntu release is no longer under LTS standard support.
---
This PR transitions the `bionic` image to `jammy` in flux-accounting and removes references of `bionic` in the `docker/` directory's README.md.
> docker: transition `bionic` container to `jammy`

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
The `csv.writer` object created in `job_archive_interface.py` uses an optional argument `quotechar` that is initialized to an empty string `("")`, but the [docs](https://docs.python.org/2/library/csv.html#dialects-and-formatting-parameters) state that this must be at least a one-character string, causing some tests to fail. I think I had copied the initialization of the `csv.writer` object from somewhere when I first wrote this file, evidently not using it correctly. 🤷‍♂️ 
---
This PR just removes this optional argument from the object initialization.
> python: remove empty `quotechar` argument from `csv.writer` object initialization

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
The `rows` variable used to store the results of a number of queries to the flux-accounting database is poorly named and can be confusing to someone looking at the code for the first time (or me, who looks at this code a lot).
---
This PR just renames the `rows` variable in a number of locations in the Python bindings to something more descriptive.
> python: rename `rows` variable to something more descriptive

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1027-mf-priority-issue376.t
The multi-factor priority plugin checks a user/bank's active jobs limit when a job enters `job.validate` and will reject a job if the user/bank is currently at their max active jobs limit. Now that Flux supports job updates, previously validated jobs can re-enter `job.validate`, which breaks the plugin's assumptions that `job.validate` is only for newly submitted jobs, particularly with this check for a user/bank's active jobs count.
---
This PR adds an unpack for the **state** of a job in `job.validate` and check this state for `FLUX_JOB_STATE_NEW` *before* checking for a user/bank's active jobs count to protect it from jobs that were already validated by the priority plugin.
It also adds a small number of tests that validates the priority plugin can support job updates for job duration …
> plugin: check for `FLUX_JOB_STATE_NEW` in `validate_cb()`

- .github/workflows/main.yml
flux-accounting's GitHub actions uses a number of near-deprecated/deprecated actions that show warnings when running CI.
---
This PR just updates the workflow file for CI for flux-accounting to use newer versions of a number of actions. I've mostly tried to just copy what flux-core has in their workflow file.
One point of clarification I think I might need is on this proposed change:
```diff
- run: echo "::set-output name=tarball::$(echo flux-accounting*.tar.gz)"
+ run: echo "$(echo flux-accounting*.tar.gz)"
```
Is the new change correct? I couldn't find the flux-core equivalent via quick GitHub search.
> ci: update github actions `main.yml` file

- NEWS.md
This PR adds some release notes for flux-accounting `v0.27.0`.
Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.27.0 -m "Tag v0.27.0" && git push upstream v0.27.0
```
> NEWS: add release notes for `v0.27.0`

- t/rc/rc1-job
- t/rc/rc1-kvs
- t/rc/rc3-job
- t/rc/rc3-kvs
Problem: flux-core is migrating the content service from the broker to a broker module.
Load the content module in test rc scripts.
Ignore any errors from 'flux module load' so that flux-accounting continues to work with older flux-core versions.
I would hold off merging until it looks like flux-framework/flux-core#5435 is going to be accepted.
> testsuite: load content module in rc scripts

- t/sharness.d/flux-accounting.sh
Problem: sharness tests in the testsuite can't be run by hand because `PYTHONPATH` is not set to the in-tree accounting python path.
In `t/sharness.d/flux-accounting.sh` add a function to prepend to a colon-separated path variable if the argument is not already the first entry. Use this to prepend the in-tree python path to `PYTHONPATH`h if necessary. Also use it for `FLUX_EXEC_PATH_PREPEND` so we don't prepend the same path multiple times.
```
$ ./t1000-print-hierarchy.t  -d -v
```
or 
```
$ FLUX_TEST_VALGRIND=t ./t1000-print-hierarchy.t  -d -v
```
> testsuite: allow sharness tests to be run by hand

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
Problem: there is no easy way to develop (in a container) and this would be nice if we consider other kinds of bindings. Solution: add a .devcontainer setup.
This is the first step (I think at least) to thinking about Go bindings. I see this is a project in C++ (not C) so I'll look into good ways to do that.
> feat: developer container environment

- src/Makefile.am
- src/plugins/Makefile.am
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
As mentioned in #410, the plugin uses its own `bank_info` struct to hold user/bank information and has a number of methods for access and modification of these structs. As the plugin's feature set has grown, so have the requirements for the `bank_info` struct, resulting in a very large and hard-to-parse piece of code. It would benefit the readability of this plugin if some basic features were abstracted out to an external class that the plugin could just be `#include`d to the plugin.
---
This PR begins this process of moving some of the definitions and features related to accessing user/bank information from the plugin's internal map to an external class. `accounting.hpp` and `accounting.cpp`, in this PR, are proposed to now hold the following:
- the definition of the `Association` class, …
> plugin: add external `Association`  class to be used in plugin

- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/t1001-mf-priority-basic.t
- t/t1022-mf-priority-issue346.t
- t/t1028-mf-priority-issue385.t
There are now helper functions available for the plugin to make use of to help with lookups and access of the internal map for users and banks, but the plugin does not make use of them.
---
This PR adds a new standalone helper function to `association.cpp` called `get_association ()`, which is just a lookup function of accounting information for a user ID and an optional bank. On success, the address of the `Association` object in the plugin's internal map is returned. On failure (if the user ID cannot be found **or** a particular user ID/bank combination cannot be found), `nullptr` is returned.
A couple basic unit tests are also added for `get_association ()`.
I've also added a small commit that changes one of the parameters for a helper function that validates a queue for a given …
> plugin: improve callback for `job.validate`

- configure.ac
- src/Makefile.am
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- t/expected/plugin_state/internal_state_1.expected
- t/expected/plugin_state/internal_state_3.expected
- t/t1019-mf-priority-info-fetch.t
The plugin defines a number of helper functions inside the plugin itself to help convert flux-accounting data to JSON format. It would significantly clean up the code if this was moved out of the plugin, especially considering it concerns flux-accounting data specifically.
---
This PR looks to do exactly that. This PR moves the helper functions responsible for creating JSON objects of all of the flux-accounting data in the plugin to `accounting.cpp`.
In the `Association` class, I've added a `.to_json ()` method which converts the object to JSON format. I've also added a new function, `converted_map_to_json ()`, which iterates through all users in the plugin's internal map and creates a JSON object containing all of its information.
As a result, the callback for `plugin.query` is also …
> plugin: move helper functions for `plugin.query` callback

- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
The `split_string ()` helper function can only accept a list of queues to parse when unpacking user/bank information from the
flux-accounting DB, but there will also exist a need in the future to be able to parse other string lists as well (e.g projects). Since both lists can be parsed the same way, this helper function should be expanded. Also, this helper function is specific to parsing flux-accounting data. It might make more sense to instead place this in `accounting.cpp`.
---
This PR moves the function definition out of the priority plugin code and into `accounting.cpp`. It also expands the `split_string ()` helper function to accept a general string list of items and renames it to `split_string_and_push_back ()`.
A unit test is also added for this function.
> plugin: move `split_string ()` out of plugin code

- src/plugins/mf_priority.cpp
Continuing the cleanup and abstraction of the code within the priority plugin, this time for the `job.new` callback.
---
This PR cleans up the callback for `job.new` by using the new external functions that perform lookups of an association. It removes unused variables from the function. It also adds a function description at the top and some additional comments within the function. Finally, it fixes some misaligned and extra whitespace.
Fixes #419
> plugin: improve callback for `job.new`

- src/plugins/mf_priority.cpp
Continuing the cleanup of the priority plugin code by utilizing the external functions defined in `accounting.cpp`.
---
This PR continues to clean up the plugin code by improving the callbacks for `job.update` and `job.update.attributes.system.queue`. Specifically, it removes the use of the clunky `get_bank_info ()` helper function defined in the plugin itself and instead uses the lookup function defined in `accounting.cpp`. The function descriptions and comments are updated in both functions, as well as some variable names. Finally, the `get_bank_info ()` helper function and its associated `typedef` and `enum`s are removed from the plugin code, since they are no longer needed.
Fixes #422
> plugin: improve `job.update`/`job.update...queue` callbacks

- NEWS.md
There are no release notes for flux-accounting `v0.30.0`.
---
This PR adds some release notes. None of the currently open PRs are necessarily required to be landed before this can go in. I've set the release date to Monday, though, just in case. 👍
> NEWS: add release notes for `v0.30.0`

- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/t1027-mf-priority-issue376.t
Continuing to move/abstract things out of the plugin code and into `accounting.*`.
---
This PR moves the `get_queue_info` and `check_map_for_dne_only ()` definitions out of the plugin code and into the `accounting.*` files. It also converts the `struct queue_info` into a class `Queue` to match the structure of `class Association`.  It improves some of the comments in the `get_queue_info ()` function and cleans up a little bit of the `if-else` checks as well. Unit tests are also now added for the `get_queue_info ()` function.
A couple of unused helper functions previously defined in the plugin code `split_string ()` and `check_queue_factor ()` are also removed from the plugin code since they are no longer needed.
Fixes #426
> plugin: move flux-accounting-specific helper functions, remove unused ones

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1032-mf-priority-update-bank.t
- t/t1033-mf-priority-update-job.t
_this is a re-implementation of the changes proposed in #400 now that the priority plugin has been changed to make use of the new classes and external functions defined in `accounting.cpp`._
flux-accounting currently has no support for a user/bank to update the bank they want their pending job to run under.
---
This is a PR that adds support for updating the bank of a pending job. It adds a new callback to the plugin which looks for the `"job.update.attributes.system.bank"` topic string and validates the new bank that the user is trying to update their job to. If they have access to the bank they want to update their job to _but_ this new bank is currently at its max running jobs or active jobs limits, the plugin will reject the update. Since `job.state.depend` is the final place where a …
> plugin: add support for updating the bank of a pending job

- src/plugins/mf_priority.cpp
The `add_missing_bank_info ()` function is defined in the "Callbacks" section of the plugin code when it is really a helper function. The function is also poorly named and not very reflective of what the function is actually doing.
---
This PR improves this function by moving it to the "Helper Functions" section of the plugin code as well as renames it to `add_special_association ()`. It edits the calls to this function to account for the name change and adds a function description as well.
> plugin: improve `add_missing_bank_info ()`

- t/Makefile.am
- t/expected/sample_payloads/same_fairshare.json
- t/expected/sample_payloads/small_no_tie.json
- t/expected/sample_payloads/small_tie.json
- t/expected/sample_payloads/small_tie_all.json
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1015-mf-priority-urgency.t
Some sharness tests in flux-accounting's testsuite don't contain the `active` column in the payloads that get sent to the priority plugin.
These sample payloads are starting to grow very large because they have a lot of fields per-user, and they clog up the test files.
---
This PR adds the `active` column to the key-value pairs of the test payloads that get sent to the priority plugin in the sharness tests.
It also moves these key-value pairs to separate JSON files that get loaded into their respective test files instead of creating them within the test directly.
> t: add `active` column, move sample payloads

- t/t1029-mf-priority-default-bank.t
_was working on re-implementing project support in the plugin and noticed this commit that could be broken off_
The priority jobtap plugin will soon support `jobspec-update`s of both banks and projects, and the `jobspec-update` event in the eventlog holds both of these updates on one line, which breaks the assumption in `t1029-mf-priority-default-bank.t` that the `jobspec-update` of a user's default bank will be surrounded by brackets `{}`.
---
Remove the outer brackets from the tests in `t1029-mf-priority-default-bank.t` that `grep` for a certain bank.
> `t1029`: remove brackets from `grep` tests

- src/cmd/flux-account-priority-update.py
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/expected/sample_payloads/same_fairshare.json
- t/expected/sample_payloads/small_no_tie.json
- t/expected/sample_payloads/small_tie.json
- t/expected/sample_payloads/small_tie_all.json
- t/t1001-mf-priority-basic.t
- t/t1005-max-jobs-limits.t
- t/t1012-mf-priority-load.t
- t/t1014-mf-priority-dne.t
flux-accounting has the ability to define and list projects for associations in the database, but the plugin does not know about or interact with them. Eventually, the plugin will need to support associating jobs with projects. This is the first step to getting there.
---
This PR looks to start the process of adding project support to the priority plugin by just adding project information to the flux-accounting information that gets sent from the database to the plugin. Each `Association` object now has two new member fields: `projects` and  `def_project`, fields to store their list of projects and their default project, respectively. This info, along with the list of all registered projects, is sent and unpacked and stored in the plugin. At the moment, it is not utilized anywhere in the …
> plugin: add project information to Association information in plugin

- src/plugins/mf_priority.cpp
The `projects` variable name in the `rec_update_cb ()` function is poorly named because it can cause confusion with the global variable `projects`. It should be renamed to something clearer, as it represents the projects that the association has access to.
---
This PR renames `projects`->`assoc_projects` in the `rec_update_cb ()` function.
> plugin: change `projects`->`assoc_projects` in `rec_update_cb ()`

- src/plugins/accounting.cpp
- t/expected/plugin_state/internal_state_1.expected
- t/expected/plugin_state/internal_state_3.expected
- t/t1019-mf-priority-info-fetch.t
Projects and default project information is now sent to the plugin, but the project information for each association is not returned in the `plugin.query` callback.
---
This PR adds the `projects` and `def_project` fields to the list of information returned for each association in the `plugin.query` callback.
It also adds the `projects` and `def_project` key-value pairs to the expected files for `t1019-mf-priority-info-fetch.t`. It adds some projects to one of the associations in the test and ensures those projects show up when looking at the ouptut of the `plugin.query` callback.
> `plugin.query`: add projects, def_project to the information returned

- NEWS.md
flux-accounting has no release notes for `v0.31.0`.
---
This PR adds some release notes. ~~Leaving as [WIP] until #437 lands.~~
> NEWS: add release notes for `v0.31.0`

- src/cmd/flux-account-priority-update.py
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/expected/plugin_state/internal_state_1.expected
- t/expected/plugin_state/internal_state_3.expected
- t/t1019-mf-priority-info-fetch.t
~~_note: will keep this as [WIP] until after the next flux-accounting release targeted for next week_~~
As mentioned in #436, the priority plugin currently does not have any information about max nodes counts per-association, which it will need in order for it to enforce a max nodes limit. The limit already exists per-association in the flux-accounting DB, so it just needs to be added to the other info that is sent during an update.
---
This PR does just that - it adds `max_nodes` to the set of information that is sent per-association from the flux-accounting DB to the plugin. Adjustments to the `Association` class, the callback responsible for unpacking flux-accounting data, the callback responsible for returning loaded flux-accounting information (`plugin.query`), and appropriate tests …
> plugin: add `max_nodes` as an attribute per-association in plugin

- t/t1011-job-archive-interface.t
- t/t1016-export-db.t
- t/t1022-mf-priority-issue346.t
- t/t1027-mf-priority-issue376.t
- t/t1028-mf-priority-issue385.t
Some of the descriptions of the sharness tests in flux-accounting are misleading because they were copied over from another test file and were never updated.
---
This PR updates the descriptions of a number of the sharness tests.
> t: update descriptions of sharness tests

- doc/guide/accounting-guide.rst
flux-accounting has a guide in flux-docs, which can be tedious to maintain when things change here in this repo.
---
This PR adds the flux-accounting guide to this repository in a newly-created `doc/` folder, following a similar format to flux-core. It also removes the flux-accounting version number from the guide.
Lastly, I've added a commit to update the instructions on running commands to populate the flux-accounting DB with job records now that #357 has landed.
> repo: create a `doc` folder, add flux-accounting guide

- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
- t/t1008-mf-priority-update.t
- t/t1013-mf-priority-queues.t
- t/t1015-mf-priority-urgency.t
- t/t1019-mf-priority-info-fetch.t
- t/t1020-mf-priority-issue262.t
- t/t1021-mf-priority-issue332.t
- t/t1022-mf-priority-issue346.t
- t/t1027-mf-priority-issue376.t
- t/t1028-mf-priority-issue385.t
- t/t1029-mf-priority-default-bank.t
- t/t1030-mf-priority-update-queue.t
- t/t1031-mf-priority-issue406.t
- t/t1032-mf-priority-update-bank.t
- t/t1033-mf-priority-update-job.t
Problem: Guest user access to the job-exec 'testexec' implementation will soon be denied by default, but many tests in the flux-accounting testsuite require such access to test multiuser jobs without access to a system instance.
For all tests that require the testexec implementation, set
[exec.testexec]
allow-guests = true
so that these tests continue working after changes in flux-core deny guest access.
This is necessary for flux-accounting tests to pass in flux-framework/flux-core#5961
> testsuite: enable guest access to testexec

- src/bindings/python/fluxacct/accounting/__init__.py.in
The schema version of the flux-accounting database was never updated with the addition of the jobs table in #357. As a result, when newer versions of flux-accounting are installed on a system, the automatic update of the database is never triggered by the background processes of flux-accounting.
---
This PR updates the schema version number of the flux-accounting database.
> database: update schema version

- t/t1005-max-jobs-limits.t
- t/t1011-job-archive-interface.t
- t/t1012-mf-priority-load.t
- t/t1013-mf-priority-queues.t
- t/t1014-mf-priority-dne.t
- t/t1018-mf-priority-disable-entry.t
- t/t1019-mf-priority-info-fetch.t
- t/t1020-mf-priority-issue262.t
- t/t1022-mf-priority-issue346.t
- t/t1028-mf-priority-issue385.t
As mentioned in #390, there are some tests in the flux-accounting testsuite that might produce a race condition when run under `valgrind`. Some of the tests look at specific job states, but there is a chance the job may not have reached a certain state, like DEPEND, by the time `flux job info` is run. It might be better to use `flux job wait-event` to look for `depend` or `alloc` events instead of looking at DEPEND or RUN states of jobs.
---
This PR makes a number of changes to the testsuite so that flux-accounting tests can be run under `valgrind`. The first commit changes the checks for certain job states to use `flux job wait-event` and `flux job info $jobid eventlog` to check for certain events and states in the tests.
The next commit removes a couple of checks for specific job usage …
> testsuite: change check for specific job states

- t/t1001-mf-priority-basic.t
- t/t1005-max-jobs-limits.t
- t/t1011-job-archive-interface.t
- t/t1012-mf-priority-load.t
- t/t1013-mf-priority-queues.t
- t/t1014-mf-priority-dne.t
- t/t1018-mf-priority-disable-entry.t
- t/t1019-mf-priority-info-fetch.t
- t/t1020-mf-priority-issue262.t
- t/t1022-mf-priority-issue346.t
- t/t1027-mf-priority-issue376.t
- t/t1028-mf-priority-issue385.t
- t/t1029-mf-priority-default-bank.t
- t/t1030-mf-priority-update-queue.t
- t/t1031-mf-priority-issue406.t
- t/t1032-mf-priority-update-bank.t
- t/t1033-mf-priority-update-job.t
- t/t1034-mf-priority-config.t
There are a number of tests in the flux-accounting testsuite that still use `flux job cancel`, but this is outdated in favor for `flux cancel`.
---
This PR replaces the use of `flux job cancel` with `flux cancel` in the flux-accounting testsuite.
> testsuite: replace `flux job cancel` --> `flux cancel`

- NEWS.md
There are no release notes for flux-accounting `v0.33.0`.
---
This PR adds some release notes. I'll create an annotated tag for this release with:
```
git tag -a v0.33.0 -m "Tag v0.33.0" && git push upstream v0.33.0
```
> NEWS: add release notes for `v0.33.0`

- src/plugins/mf_priority.cpp
There are a couple of unused iterator variables left over in the callback for `job.state.inactive` that were never removed when I was cleaning up and abstracting stuff out of the plugin and into an external class.
---
This PR removes these unused iterator variables.
> `inactive_cb`: remove unused iterator variables

- src/plugins/mf_priority.cpp
Mentioned as possible cleanup in #455, the weight of each factor is checked every time the priority of a job is calculated. It would be cleaner to put this check somewhere else so it does not need to be repeated for every job.
---
This PR creates defaults for the weights of each factor used in the priority calculation of a job and initializes each weight when the plugin is first loaded. In the callback for `conf.update`, it then checks to see if these weights have been configured; if not, it will just continue to use the defaults defined at the top of the file.
> plugin: initialize factor weights on plugin load

- doc/guide/accounting-guide.rst
- src/bindings/python/fluxacct/accounting/job_archive_interface.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/scripts/insert_jobs.py
- t/t1026-flux-account-perms.t
- t/t1035-flux-account-scrub-old-jobs.t
As it stands right now, the `jobs` table in the flux-accounting database grows without bound as more and more jobs finish running and are fetched by flux-accounting. However, at a certain point, job records become irrelevant for flux-accounting in terms of calculating job usage and fair-share values.
---
This PR adds a new command to flux-accounting called `scrub-old-jobs` which takes an integer argument representing the number of weeks to go back. It will remove any job records older than the number of weeks passed
in, e.g `flux account scrub-old-jobs 4` will remove any job older than 4 weeks old. If no argument is specified, the default will be 26 weeks (or 6 months).
Some basic sharness tests are added that add some fake job records to the flux-accounting database and run the …
> database: add the ability to remove old job records from `jobs` table

- src/bindings/python/fluxacct/accounting/job_archive_interface.py
There are a few functions in `job_archive_interface.py` that could use some improvements to their error handling and parameter and string construction. There's also some opportunity for some duplicate code cleanup.
---
This PR just makes some minor cleanup in a couple of functions in `job_archive_interface.py`. Notably, it reduces a couple of unnecessary checks in `get_job_records()` and makes use of f-strings for the query construction.
Some duplicate code is cleaned up in the helper functions for filtering jobs by default/secondary banks by reducing them into just one `filter_jobs_by_bank()` function.
Some more explicit error handling is added to `add_job_records()` to handle the case where the construction of a `ResourceSet` object fails while parsing job records.
> job archive interface: clean up a couple helper functions

- NEWS.md
There are no release notes for `v0.34.0`.
---
```
git tag -a v0.34.0 -m "Tag v0.34.0" && git push upstream v0.34.0
```
> NEWS: add release notes for `v0.34.0`

- src/plugins/mf_priority.cpp
The format string for unpacking the various weights for priority factors in a config file is missing a closing bracket.
---
This PR adds it.
As an aside, I'm not sure why the testsuite never caught this before. I have a dedicated testing file for `conf_update_cb ()` (`t1034-mf-priority-config.t`) that **should** be testing different configuration files, but apparently it passed all of those. Is there maybe a different kind of test I could add that maybe comprehensively checks the format string? 🤷
> `conf.update`: add missing bracket in format string

- t/sharness.d/flux-accounting.sh
Problem: When flux-accounting is already installed on a system, the sharness tests pull in the installed version of flux-accounting Python modules instead of the test version. This occurs because sharness prepends the source tree Python path to PYTHONPATH, which is then subverted by flux-core's `py-runner.py`, which prepends the system path in front of that before executing Python subcommands like the accounting service etc.
Use FLUX_PYTHONPATH_PREPEND instead of PYTHONPATH, which is preserved by the py-runner.py wrapper.
> testsuite: fix on systems with flux-accounting already installed

- NEWS.md
There are no release notes for flux-accounting `v0.35.0`.
---
This PR adds some release notes. I'll create an annotated tag once this lands with:
```
git tag -a v0.35.0 -m "Tag v0.35.0" && git push upstream v0.35.0
```
> NEWS: add release notes for `v0.35.0`

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
The function descriptions for a number of functions in the Python bindings do not follow [PEP 257: Docstring Conventions](https://peps.python.org/pep-0257/).
---
This PR updates the misformatted function description to follow docstring convention.
> python: change function descriptions to follow docstring convention

- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
- src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
There are still a couple function descriptions in the Python bindings that do not follow docstring convention [PEP257](https://peps.python.org/pep-0257/).
---
This PR updates the misformatted function description to follow docstring convention before the formatting police come after me.
> python: convert more function descriptions to docstring format

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1023-flux-account-banks.t
There is currently no way to list the current banks defined in the `bank_table` in the flux-accounting database, especially in a
convenient format like JSON.
---
This PR adds a new command to the flux-accounting command suite called `list-banks`. When called, this command will create a JSON object containing all of the active banks in the `bank_table`. Below is example output of `flux account list-banks`:
```json
[
{
"bank_id": 1,
"bank": "root",
"parent_bank": "",
"shares": 1,
"job_usage": 0.0
},
{
"bank_id": 2,
"bank": "A",
"parent_bank": "root",
"shares": 1,
"job_usage": 0.0
},
{
"bank_id": 3,
"bank": "B",
"parent_bank": "root",
"shares": 1,
"job_usage": 0.0
}
]
```
Passing `--inactive` will include *all* banks, even those which have been disabled. The fields output in the JSON object …
> `bank_table`: add a new `list-banks` command

- src/cmd/flux-account-fetch-job-records.py
There is a case where a job can have an `R` but not have entered `RUN` state, and thus, does not receive a `t_run` time. The `flux account-fetch-job-records` script does not verify that the timestamp key-value pairs exist before attempting to insert them into the `jobs` table in the flux-accounting DB, which can result in a `KeyError`.
---
This PR adds two integrity checks for job records fetched by this script:
- When initially fetching jobs that checks that each key-value pair exists before adding it to a list of fetched job records, if a key-value pair is not valid, skip adding the job.
- When attempting to insert a job record into the `jobs` table, wrap the `INSERT` in a try-except block in case a `KeyError` is raised. If so, just skip adding the job.
> `fetch-job-records`: add integrity check for records

- NEWS.md
There are no release notes for `v0.36.0`.
---
```
git tag -a v0.36.0 -m "Tag v0.36.0" && git push upstream v0.36.0
```
> NEWS: add release notes for `v0.36.0`

- src/Makefile.am
`flux_account_shares.cpp` was removed in #471, but there is still a compile definition for it in the top-level `Makefile.am` that is left over.
---
This PR just removes the left over compilation instructions.
Fixes #481
> `Makefile`: remove left over compile instructions for `flux_account_shares`

- doc/guide/accounting-guide.rst
The flux-accounting service depends on the creation of the flux-accounting DB before starting since it needs to establish a connection to the DB in order to run `flux account` commands. If this is done out of order, confusing behavior can result from running the commands, such as an `attempt to write to a readonly database` error.
---
This PR just adds a note to the flux-accounting guide about making sure the flux-accounting DB has been created before starting the flux-accounting service and gives an example of the error message that can potentially occur.
> doc: add example error message when creating DB after starting systemd service

- configure.ac
As noted in #364, flux-accounting does not check for `jansson` when running `./configure` even though it uses it in the priority plugin.
---
This PR adds a check for `jansson` in `configure.ac`.
Fixes #364
> configure: add `jansson` as a dependency check

- src/plugins/mf_priority.cpp
There are a couple callbacks in the plugin that call `flux_respond ()` before they are done processing.
---
This PR moves these calls to just before the functions call `return`.
> plugin: move `flux_respond ()` to end of functions

- NEWS.md
There are no release notes for flux-accounting `v0.37.0`.
---
This PR adds some release notes for the upcoming release after the long weekend. Once this lands, I'll complete the release with:
```
git tag -a v0.37.0 -m "Tag v0.37.0" && git push upstream v0.37.0
```
> NEWS: add release notes for `v0.37.0`

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1040-mf-priority-projects.t
The priority plugin does not do any validation or annotation for a specified _or_ default project associated with an association's jobs.
---
This PR looks to add basic support for validating a project if one is specified when submitting a job as well as adding a default project to jobspec when one is not specified. If a project is specified on the command line, it is validated by looking at the association's list of valid projects. If the specified project cannot be found, the job is rejected.
In the case where no project is specified, the association's default project is added to jobspec via `jobspec-update`, similar to how the default bank for an association is added to jobspec.
Some basic tests are also added that simulate setting project names in multiple cases - where the plugin is …
> plugin: add project validation/annotation

- src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
The `username` field is automatically populated when `userid` is passed into the construction of a `JobRecord` object, but it is listed as an attribute during initialization.
---
This PR removes `username` from the list of attributes in `__init__()`. It also explicitly labels which fields are being assigned to which member of the `JobRecord` object instead of labeling them via comments.
I've also snuck in a spelling correction commit at the end of this PR.
> JobRecord: remove `username` from `__init__()` of JobRecord object

- src/plugins/mf_priority.cpp
The callback for `job.state.inactive` does not `return -1` in the event of an exception being raised due to failing to remove a dependency from a held job for an association.
---
Add a `return -1` call after `flux_jobtap_raise_exception ()` in the callback for `job.state.inactive`.
> `job.state.inactive`: add `return -1` to exception

- NEWS.md
There are no release notes for flux-accounting `v0.38.0`.
---
This PR adds some release notes for `v0.38.0`. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.38.0 -m "Tag v0.38.0" && git push upstream v0.38.0
```
> NEWS: add release notes for `v0.38.0`

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1007-flux-account-users.t
- t/t1036-hierarchy-small-no-tie-db.t
- t/t1037-hierarchy-small-tie-db.t
- t/t1038-hierarchy-small-tie-all-db.t
There are multiple `--parsable` optional arguments throughout the flux-accounting command suite, but the spelling for it in the view-user command is not consistent and is spelled `--parseable`. Technically, both spellings are correct, but they should be made consistent throughout the command suite.
---
This PR just changes the spelling of the `--parseable` optional argument for `view-user` to `--parsable`.
> `view-user`: make "parsable" spelling consistent

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- t/python/t1005_project_cmds.py
- t/t1025-flux-account-projects.t
For some reason, the unit tests for the project subcommands was just a duplicate of the functions for the subcommands themselves instead of the actual unit tests, and I never noticed. I must have botched something when I moved them from the `accounting` directory to the `t/` directory.
Passing `-1` for the `--projects` optional argument in the `edit-user` command does not work because the `edit_user()` function thinks that `-1` is a project name, so it doesn't actually reset the projects list to just `*`.
---
This PR does a couple of minor things. It adds the missing unit tests to `t1005_project_cmds.py`. And it adds a check for `-1` in the projects portion of `edit_user()` to reset the `projects` field to just `*`. I've added both a unit test and sharness test to make sure this works as …
> projects: fix unit tests for project subcommands, `--projects` reset capability

- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1025-flux-account-projects.t
There currently exists no way to list all of the currently registered projects in the flux-accounting database.
---
This PR adds a new command to the flux-accounting command suite, `list-projects`, that creates a table of all of the currently registered projects in the flux-accounting database.
I've also added a couple sharness tests to `t1025-flux-account-projects.t` that check the output of calling `list-projects` with just the default project listed and after registering a couple of other projects.
> command suite: add new `list-projects` command

- src/plugins/mf_priority.cpp
The priority plugin uses the same exception message for jobspec updates in more than one callback because there is more than one instance where that message would be appropriate. However, these exception messages are not prefixed with the callback the exception is being raised from, which can make it hard to debug when looking at a job's eventlog.
---
This PR just adds a prefix of the name of the callback the exception message is coming from.
> plugin: add callback prefixes to exception messages

- doc/guide/accounting-guide.rst
The flux-accounting guide does not detail how to manually load the priority plugin if the path to the plugin is not configured in the job-manager config file.
---
This PR just adds a note that the plugin can be loaded manually with `flux jobtap load`. It includes the `flux account-priority-update` command so admins know to send flux-accounting information to the plugin once it is loaded.
Fixes #497
> doc: add note about manually loading plugin

- .readthedocs.yaml
- doc/conf.py
- doc/index.rst
flux-accounting currently has "official" documentation over in flux-framework/flux-docs, but for the flux-accounting guide (and other related documentation that could come in the future), it should follow flux-core's documentation configuration, which has guides hosted in its own repository and ReadTheDocs project that can then be linked to by flux-docs.
---
This PR looks to do add ReadTheDocs support for the flux-accounting repository. I've added a `.readthedocs.yaml` config file as well as added a link to `index.rst` to the flux-accounting guide hosted in this repository.
Once landed, I think all I need to do is go on the ReadTheDocs site and add this repository as a new project (at least, that was all I had to do in my local fork). Then I think I'd need to open a PR in flux-docs to …
> doc: add ReadTheDocs support for flux-accounting

- .github/workflows/main.yml
- .typos.toml
- config/ax_flux_core.m4
- doc/test/spell.en.pws
- doc/test/spellcheck
- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account-service.py
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- src/test/checks_run.sh
- t/t1005-max-jobs-limits.t
- t/t1025-flux-account-projects.t
- t/t1033-mf-priority-update-job.t
flux-accounting does not have a spellchecker that runs on pull requests.
---
This PR adds a spellchecker as another builder during CI. As a result of the spellchecker running (and my horrendous spelling), I've also fixed all of the spelling mistakes flagged by the spellchecker throughout flux-accounting. Like flux-core, I've removed `IPv4` and `IPv6` from the dictionary. Finally, I've added `"dne"`, `"DNE"`, and `"fairshare"` as acceptable words.
> ci: add spellchecker to flux-accounting

- doc/guide/accounting-guide.rst
The flux-accounting guide does mention the ability to configure the weights of each factor used in the multi-factor priority calculation of a job's priority in the plugin.
---
This PR adds a note about configuring the factor weights in the priority plugin.
Fixes #502
> guide: add note about configuring factor weights

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- t/Makefile.am
- t/python/t1002_user_cmds.py
- t/python/t1003_bank_cmds.py
- t/t1042-issue508.t
Mentioned in #508, the structure of the flux-accounting database hierarchy of banks and users assumes there is only one root bank (e.g when calculating fair-share), but multiple root banks can be added with the `add-bank` command.
---
This PR adds a check when adding a root bank that one does not already exist. If so, an exception is raised.
A couple of existing tests that did not make this assumption have been edited to account for this new check, and I've also added a simple sharness test that ensures an exception is raised when trying to add more than one root bank.
Fixes #508
> `add-bank`: add a check when adding a root bank

- .gitignore
Git does not ignore the built documentation under `doc/_build` or the `.log` or `.trs` files as a result of running sharness tests.
---
This PR just adds the docs intermediate files and sharness test result files to the list of ignored files by Git.
> `.gitignore`: add built docs, sharness test results

- doc/guide/accounting-guide.rst
Problem: the accounting guide uses words to describe how priority is calculated but math would be clearer.
Add "queue" to the lists of factors and format the list as a dictionary rather than a bullet list.
Use a math expression for the priority value.
I briefly looked at the code and priority appeared to be calculated this way - did I get it right?
> doc: add priority equation to accounting guide

- src/cmd/flux-account-fetch-job-records.py
`flux account-fetch-job-records` uses `flux.job.job_list_inactive()` to fetch all jobs that have finished since a certain time. However, it does not set a value for `max_entries`, which defaults to 1000. This would mean that it could miss fetching certain jobs if more than 1000 completed since a certain time.
---
This PR sets `max_entries` to 0 to get all jobs that have finished since a certain timestamp.
Fixes #515
> fetch-job-records: set `max_entries=0`

- src/bindings/python/fluxacct/accounting/user_subcommands.py
Since the formatting of the columns in the output of `view-user --parsable` is dependent on the length of the longest column name, the width of every column is forced to match, which can result in some ugly screen wrapping even in a relatively small font.
```console
$ flux account view-user moussa1 --parsable
creation_time   mod_time        active          username        userid          bank            default_bank    shares          job_usage       fairshare       max_running_jobsmax_active_jobs max_nodes       queues          projects        default_project 
1661527404      1661527404      1               moussa1         58985           lc              lc              1               0.0             0.457547        100             1000            2147483647                      * …
```
> `view-user --parsable`: improve output formatting

- t/t1011-job-archive-interface.t
Mentioned in #517, `t1011-job-archive-interface.t` relies on the job-archive module
in flux-core which is being considered for removal in
https://github.com/flux-framework/flux-core/pull/6378 since flux-accounting now has that
capability on its own.
---
This PR adds a check in `t1011-job-archive-interface.t` that will skip the test file in the event that the job-archive module does not exist.
I've also added a new file to the test suite that very similarly runs through the same tests in `t1011` but does not rely at all on the detection of the job-archive module.
> t: skip t1011 if job-archive module not detected, add new tests for `fetch-job-records`

- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
`flux-account.py` manually creates the dictionary of arguments that is sent via RPC to the flux-accounting service, but since the service already unpacks these arguments, `flux-account.py` can just create a dictionary of the arguments using `vars()` and send the dictionary without having to define each key-value pair before sending the RPC.
---
This PR changes `flux-account.py` to just use `vars()` on the parsed args to create a dictionary before sending the RPC to the appropriate flux-accounting command.
> `flux-account.py`: get rid of dictionary initialization

- src/bindings/python/fluxacct/accounting/__init__.py.in
- src/bindings/python/fluxacct/accounting/create_db.py
- src/cmd/flux-account-fetch-job-records.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account-update-db.py
- src/cmd/flux-account.py
The constants defined in `__init__.py` for the flux-accounting Python package are formatted incorrectly and are flagged by `pylint`. They should be in all caps:
```
__init__.py:1:0: C0103: Constant name "db_dir" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
__init__.py:2:0: C0103: Constant name "db_path" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
__init__.py:3:0: C0103: Constant name "db_schema_version" doesn't conform to '(([A-Z_][A-Z0-9_]*)|(__.*__))$' pattern (invalid-name)
```
---
This PR fixes the format of the constants defined in `__init__.py` and changes the references to these constants throughout the Python package to account for the change.
> `__init__.py`: fix formatting of constants

- src/bindings/python/fluxacct/accounting/Makefile.am
- src/bindings/python/fluxacct/accounting/__init__.py.in
- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/sql_util.py
- t/Makefile.am
- t/python/t1007_formatter.py
flux-accounting has lots of different tables that can be viewed with `view-*` and `list-*` commands, but each one has its own function that could probably be cleaned up with some common utility. Better yet, if the formatting options for all of these commands was centralized, it might make for easier changes in the future and/or customization of output by users.
---
This PR begins to centralize the formatting for flux-accounting by adding a new `AccountingFormatter` class to the Python bindings. The class takes a SQLite `Cursor` object that has the results of running a query on the flux-accounting database and offers two methods of formatting its data: data in an adjustable table or data in JSON format. Since this class just takes a `Cursor` object, this means it can support customization …
> python: add `AccountingFormatter` class, SQLite utility file

- src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
- src/cmd/flux-account.py
- t/python/t1006_job_archive.py
The `convert_to_str()` function used to convert a list of `JobRecord` objects to a string does not actually convert it to a string, but rather just appends separate strings to a list and then returns a list. Thus, `flux-account.py` has to have some special logic for just the `view-job-records` command to parse the returned data from the function.
---
This PR adds a `.join()` call to the `convert_to_str()` function to actually construct a string of all of the job records returned by `view_jobs()`. It also removes the special logic in `flux-account.py` that iterates through the list of job records and prints it out since it is no longer needed. I've also adjusted the unit tests in `t1006_job_archive.py` to use a better function in `jobs_table_subcommands.py`, as well as fixed a test …
> `view_jobs()`: adjust helper function to actually return a string

- NEWS.md
There exists no release notes for flux-accounting `v0.39.0`.
---
```
git tag -a v0.39.0 -m "Tag v0.39.0" && git push upstream v0.39.0
```
> NEWS: add release notes for `v0.39.0`

- t/t1023-flux-account-banks.t
There is a test in `t1023-flux-account-banks.t` that makes sure the default bank of a user is updated when one of their user/bank rows is deleted from the database by removing it in the test prior, but the wrong user is deleted.
---
This PR just changes which user is deleted in `t1023-flux-account-banks.t`.
> t: change which user is deleted from association_table

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
The `list-banks` command defines its own formatting for the output of the command, but the Python bindings now has its own common formatter and SQL utilities.
---
This PR edits the `list-banks` command to make use of the new formatter and external SQLite utilities. It also changes the default for the `--fields` optional argument to be `None` if it is not specified.
> `list-banks`: use `AccountingFormatter` class

- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1007-flux-account-users.t
The `--username` and `--bank` arguments for `add-user` should be required arguments, but they are currently treated as optional arguments. This means that if someone calls add-user without passing `--username` or `--bank`, the corresponding `add_user()` function will try to run the function with `None` values. Requirements should be added for both of these arguments at the top level so that the call fails if either one of these is not present.
---
This PR adds `required=True` to both the `--username` and `--bank` arguments in `add-user`. I've also added two tests to `t1007-flux-account-users.t` to make sure errors are raised when either one of these is missing from the `add-user` call.
Fixes #531
> `add-user`: make `--username` and `--bank` required arguments

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1021-mf-priority-issue332.t
The `edit_user()` function is clunky and could stand to undergo some improvements. Namely:
- the reset behavior for editable fields is inconsistent. For example, an association's `projects` list can be reset with `-1`, but their `queues` list is reset with an empty string.
- the function parameters define every editable field in the signature when it really could just use `**kwargs`.
- The function allows `bank` to be edited for an association, which should not be allowed since associations, once created, are not deleted because they can continue to contribute to a bank's fair-share (up to the job usage reset period).
---
This PR changes the function's signature to use `**kwargs` for the editable fields and removes "bank" as an editable field for an association. It also unifies the reset …
> `edit-user`: unify reset behavior, `**kwargs` for editable fields

- NEWS.md
There are no release notes for flux-accounting `v0.40.0`.
---
```
git tag -a v0.40.0 -m "Tag v0.40.0" && git push upstream v0.40.0
```
> NEWS: add release notes for `v0.40.0`

- t/valgrind/valgrind.supp
Problem: changes proposed to flux-core introduce a new "false positive" valgrind error.
Bring over the suppression proposed in core.
> testsuite: pull in valgrind suppression from core

- .github/workflows/main.yml
The `"python-format"` GitHub action fails with:
> Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
because Python 3.7 has reached its EOL: https://github.com/actions/setup-python/issues/962.
---
This PR fixes the version of Ubuntu for the `"python-format"` action to `20.04` instead of using `ubuntu-latest`.
> github: fix ubuntu version for `"python-format"` action

- doc/guide/accounting-guide.rst
There are no examples or explanations in the documentation of how flux-accounting's priority plugin can enforce permissions for associations on certain queues by setting them up in flux-accounting.
---
This PR adds some documentation explaining how to set this up. I've also included a simple example of configuring an association's list of permissible queues and how a job gets rejected if they submit a job to a queue they do not have access to.
Fixes #549
> doc: add section on configuring queue permissions

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/formatter.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/expected/flux_account/A_bank.expected
- t/expected/flux_account/D_bank.expected
- t/expected/flux_account/E_bank.expected
- t/expected/flux_account/F_bank_tree.expected
- t/expected/flux_account/F_bank_users.expected
- t/expected/flux_account/full_hierarchy.expected
- t/expected/flux_account/root_bank.expected
- t/expected/pop_db/db_hierarchy_base.expected
- t/expected/pop_db/db_hierarchy_new_users.expected
- t/expected/print_hierarchy/small_no_tie.txt
- t/expected/print_hierarchy/small_tie.txt
- t/expected/print_hierarchy/small_tie_all.txt
- t/expected/update_fshare/post_fshare_update.expected
- t/expected/update_fshare/pre_fshare_update.expected
- t/python/t1008_banks_output.py
- t/t1023-flux-account-banks.t
- t/t1036-hierarchy-small-no-tie-db.t
- t/t1037-hierarchy-small-tie-db.t
- t/t1038-hierarchy-small-tie-all-db.t
The `AccountingFormatter` class has good overarching methods for printing the results of a query to the flux-accounting database, but there is some functionality specific to viewing bank information from the database that could use its own subclass.
---
This PR adds a new subclass called `BankFormatter`, which contains unique methods for viewing bank/user information in hierarchical and parsable formats with the `view-bank` command, particularly with the `--tree`, `--users`, and `-P` options. A new `--fields` option is also added to match the customization available in the `list-banks` command. It removes the helper functions previously defined in `bank_subcommands.py` in favor of using this new subclass.
I've added some new unit tests for the output of the reworked `view-bank` command to …
> python: create new `BankFormatter` subclass, restructure `view-bank` to use new class

- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/python/t1009_users_output.py
- t/t1007-flux-account-users.t
- t/t1011-job-archive-interface.t
- t/t1023-flux-account-banks.t
- t/t1025-flux-account-projects.t
The `view_user()` function manually defines its own print functionality for viewing information about an association in the
flux-accounting database, but the Python bindings have its own formatting class that does this. It's also tedious to add new formatting features to the `view_user()` function.
---
This PR creates a new subclass of `AccountingFormatter` called `AssociationFormatter`. It has a unique error message when the user cannot be found in the `association_table`, but otherwise inherits the default JSON and table outputs that the `AccountingFormatter` class already provides. Thus, the various helper functions used to create output for the `view_user()` functions could be removed.
I've edited a number of tests in the testsuite that check for specific output from the `view-user` …
> `view-user`: create new `AssociationFormatter` subclass for viewing associations

- t/t1001-mf-priority-basic.t
- t/t1002-mf-priority-small-no-tie.t
- t/t1003-mf-priority-small-tie.t
- t/t1004-mf-priority-small-tie-all.t
- t/t1005-max-jobs-limits.t
- t/t1008-mf-priority-update.t
- t/t1011-job-archive-interface.t
- t/t1012-mf-priority-load.t
- t/t1013-mf-priority-queues.t
- t/t1015-mf-priority-urgency.t
- t/t1019-mf-priority-info-fetch.t
- t/t1020-mf-priority-issue262.t
- t/t1021-mf-priority-issue332.t
- t/t1022-mf-priority-issue346.t
- t/t1027-mf-priority-issue376.t
- t/t1028-mf-priority-issue385.t
- t/t1029-mf-priority-default-bank.t
- t/t1030-mf-priority-update-queue.t
- t/t1031-mf-priority-issue406.t
- t/t1032-mf-priority-update-bank.t
- t/t1033-mf-priority-update-job.t
Some of the tests in the testsuite can be somewhat complex and simulate a scenario that might take multiple steps; it would be helpful if descriptions were added that went into more detail than what is described in the one-liner for each test.
---
This PR makes a number of minor test description improvements in the flux-accounting testsuite, most notably adding some more thorough test descriptions in a couple of the test files explaining what is being tested, particularly for the scenarios that are broken up over multiple tests.
I've also fixed a couple of mistakes in the test description and in already-existing test comments.
Lastly, I've just added a space between the `"allow guest access..."` tests to match the format of the rest of the testsuite.
Built on top of #547
> testsuite: add longer test descriptions for some of the more complex test scenarios

- src/Makefile.am
- src/plugins/Makefile.am
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/jj.cpp
- src/plugins/jj.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/Makefile.am
- t/t1044-mf-priority-resource-limits.t
The priority plugin does not keep track of the resources used by an association across all of their running jobs, which will be needed when the plugin begins to enforce limits on how many resources they can have across all of their running jobs.
---
This PR looks to add the _tracking_ component of an association's resource consumption across all of their running jobs. It does this by copying over the [jj](https://github.com/flux-framework/flux-core/blob/master/src/common/libjob/jj.h) (along with a required [streq](https://github.com/flux-framework/flux-core/blob/02ad07cf4041d81253ca5765e5933c722b66d898/src/common/libccan/ccan/str/str.h#L10) function) code over from flux-core and utilizing the `jj_get_counts_json ()` function to get a total `nnodes` and `ncores` count. When a job enters …
> plugin: track the resources used across all of an association's running jobs

- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1045-issue478.t
Mentioned in #478, there is no concise way to just view a list of banks that a user belongs to without having to parse through the rest of the accounting information associated with it.
---
This PR adds a new optional argument to `view-user` called `--list-banks`, which just outputs a newline-delimited list of banks that a user belongs to.
```console
$ flux account view-user testuser --list-banks
bankA
bankB
bankC
```
A basic test file is also added which calls this optional argument. For now, this is just built on top of #477, but I can always make it separate in case this gets reviewed first. :-)
Fixes #478
> `view-user`: add a new `--list-banks` optional argument

- doc/components/fair-share.rst
- doc/index.rst
flux-accounting doesn't really have any in-depth documentation about how fair-share is calculated for a hierarchy of banks and users.
---
This PR adds some documentation about how fair-share is calculated for a hierarchy of banks and users in flux-accounting. I've also created a small example hierarchy and walked through the process of calculating fair-share for an association.
> doc: add fair-share documentation

- src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1046-issue565.t
The `--after-start-time` and `--before-end-time` optional args for the `view-job-records` command only takes one format: a seconds-since-epoch timestamp, which isn't super user friendly.
---
This PR makes use of the `flux.util.parse_datetime()` function to accept multiple, more human-readable format strings as values to the `--after-start-time` and `--before-end-time` optional args.
It adds a helper function to `jobs_table_subcommands` to perform the parsing of the timestamp. If parsing the timestamp string fails, it just attempts to pass it as a seconds-since-epoch timestamp to the SQLite query (which will return no job records if the timestamp is invalid).
I've also updated the help description to both of the optional arguments to provide examples of human-readable formats as well as …
> `view-job-records`: accept multiple timestamp formats for `after-start-time`, `before-end-time` optional args

- src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
- t/Makefile.am
- t/t1047-issue564.t
As noted in #564, viewing a job record with `view-job-records --jobid` only accepts decimal formats of job IDs. However, Flux offers multiple formats for job IDs, and thus, the `--jobid` argument should also be able to handle such formats.
---
This PR adds the use of the `flux.job.JobID()` class to convert any Flux job ID format passed-in to a decimal format when looking up a job record in the flux-accounting job-archive.
I've also added in some basic tests that call `view-job-records --jobid` with different ID formats.
Fixes #564
> `view-job-records --jobid`: accept all Flux job ID formats

- t/Makefile.am
The test files in `t/Makefile.am` is missing a line continuation character between `t1008_banks_output.py` and `t1009_users_output.py`.
---
This PR adds the missing line continuation character.
> `t/Makefile.am`: add missing line continuation (`\`) character

- src/bindings/python/fluxacct/accounting/__init__.py.in
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/python/t1002_user_cmds.py
- t/t1007-flux-account-users.t
Since admins are the only ones who have privileges to run the `edit-user` command, they should be able to edit the `fairshare` column for an association manually if they so choose, but there is currently no way to do so via `edit-user`; they have to connect to a SQLite shell and create and execute a SQL statement to update the column manually.
---
This PR makes the `fairshare` column an optional argument in the `edit-user` command. I've updated the `fairshare` column in the `association_table` to match the other editable fields, as well as added a unit and sharness test.
> `edit-user`: make `fairshare` an editable field for an association

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/python/t1002_user_cmds.py
- t/t1007-flux-account-users.t
The `delete-user` command does not actually delete a row from the `association_table` but instead sets the 'active' column for a row to 0. There might be a use case where an admin would actually want to remove a row from the table.
---
This PR adds a new `--force` optional argument to the `delete-user` command which will actually remove the row from the `association_table`. I've also added a function description to `delete_user()` to describe more fully what the function does (i.e. explaining disabling vs. actually deleting a user).
I've also added a couple of unit tests and sharness tests for calling `delete-user --force`.
> `delete-user`: add `--force` option to actually remove a row from the `association_table`

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/python/t1003_bank_cmds.py
- t/t1023-flux-account-banks.t
Similar to #572, the `delete-bank` command does not actually delete a row from the `bank_table` but instead sets the 'active' column for a row to 0. There might be a use case where an admin would actually want to remove a row from the table.
---
This PR adds a new `--force` optional argument to the `delete-bank` command which will actually remove the row from the `bank_table`. I've also added a function description to `delete_bank()` to describe more fully what the function does (i.e. explaining disabling vs. actually deleting a bank).
I've also added a couple of unit tests and sharness tests for calling `delete-bank --force`, both with and without sub-banks and users in those banks.
> `delete-bank`: add `--force` option to actually remove a row from the `bank_table`

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1048-issue575.t
A job held in PRIORITY and waiting to be allocated resources gets reprioritized and sent back to `job.state.priority` or `job.priority.get` _after_ a restart (clearing its aux items) when a plugin is already loaded and seen the job.
The multi-factor priority plugin raises an exception on a job in `job.state.priority` when it cannot find the aux item containing the association information for the job. However, when a system instance is reloaded, the aux items set on a job are cleared. When jobs are reprioritized and are sent back to `job.state.priority` or `job.priority.get`, the plugin will raise an exception on the job because it can't unpack the aux item containing the flux-accounting information associated with that job. See the below eventlog for an example:
```
... …
```
> `job.state.priority`: remove raising exception when no aux item found

- NEWS.md
There are no release notes for v0.41.0.
---
This PR adds some release notes for 02-04-2025. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.41.0 -m "Tag v0.41.0" && git push upstream v0.41.0
```
> NEWS: add release notes for `v0.41.0`

- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/expected/job_usage/no_jobs.expected
- t/t1011-job-archive-interface.t
- t/t1041-view-jobs-by-project.t
The `formatter` module in flux-accounting does not have a class for formatting the output of job records which would be useful because the flux-accounting Python bindings manually define the formatting of these job records within its bindings.
---
This PR creates a new class called `JobsFormatter`, a subclass of `flux.util.OutputFormat`, which can take a Python format string to allow a user to customize their output, similar to flux-jobs:
```console
flux account view-job-records -o "{userid:<8} | {nnodes:<6} | {bank:<8}" 
userid   | nnodes | bank    
5001     | 1      | bankB   
5002     | 1      | bankB   
5002     | 1      | bankB   
5001     | 1      | bankA   
5001     | 1      | bankA 
```
`view-job-records` is restructured to use the new `JobsFormatter` class instead of defining its …
> `formatter`: add new `JobsFormatter` class, restructure `view-job-records` to use new class

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/formatter.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account-service.py
- t/python/t1001_db.py
- t/python/t1002_user_cmds.py
- t/python/t1003_bank_cmds.py
- t/python/t1004_queue_cmds.py
- t/python/t1005_project_cmds.py
- t/python/t1006_job_archive.py
- t/python/t1007_formatter.py
- t/python/t1008_banks_output.py
- t/python/t1009_users_output.py
Currently, a lot of the functions that retrieve data from the SQLite database use a raw SQL query. The results of this query are accessed using positional indexing (e.g., `row[0]`, `row[1]`, etc.), which requires prior knowledge of the column order. This approach is problematic because it makes the code harder to read and maintain, and if the database schema changes (e.g., column order is modified), the function could break or return incorrect values.
---
This PR sets the `row_factory` property for the SQLite `Connection` object created in the flux-accounting service, the bulk-update script, the `formatter` module, and the Python unit tests. As a result, a number of functions are edited to access the results of a SQL query by column name instead of by row index.
I've broken this PR into …
> python: use column names when accessing results of a query instead of row indices

- doc/Makefile.am
- doc/index_man.rst
- doc/man1/flux-account-create-db.rst
- doc/man1/flux-account-export-db.rst
- doc/man1/flux-account-pop-db.rst
- doc/man1/flux-account.rst
- doc/man1/index.rst
- doc/manpages.py
- doc/test/spell.en.pws
flux-accounting has no support for adding man(1) pages to the repository, which is needed for man pages for all of the various `flux account` subcommands.
---
This PR begins to add `man(1)` entries to the repository that can be accessed with `man flux-account`. To avoid posting a gigantic PR with many `.rst` files to read and review, I've started with adding just `man(1)` entries for all of the subcommands related to DB administration: `create-db`, `export-db`, and `pop-db`. These man pages can be accessed either with `man flux-account create-db`, `man flux-account-create-db`, or `man flux account-create-db`.
> doc: add man(1) page support, entries for DB administration subcommands

- src/fairness/reader/data_reader_db.cpp
- t/Makefile.am
- t/t1049-issue580.t
The variable that stores job usage values for banks in the update-fshare script is a 32-bit `int`, and it cannot keep up with larger job usage values that are generated on big machines.
---
This PR changes the variable type of the job usage value from a 32-bit `int` to a 64-bit `double`. This variable probably should have been a `double` this whole time because the job usage value for an association or bank is not always guaranteed to be a whole number. 
I've also added a test that updates the fair-share value for an association and bank where the job usage value is gigantic.
> `update-fshare`: change job usage variable from 32-bit `int` to `double`

- NEWS.md
There are no release notes for flux-accounting `v0.42.0`.
---
This PR adds some release notes for flux-accounting `v0.42.0`. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.42.0 -m "Tag v0.42.0" && git push upstream v0.42.0
```
This should not be landed until #581 has been merged.
> NEWS: add release notes for v0.42.0

- .github/workflows/main.yml
There are a couple of GitHub actions that use `ubuntu-20.04`, but this version will no longer be supported in April 2025. They also use versions of Python that are not found on later versions of Ubuntu. The `pylint` GitHub action also no longer works with a newer version of Python > 3.10: https://stackoverflow.com/questions/78459119
---
This PR updates the actions to use `ubuntu-latest` and updates the version of Python used in the `python format` and `pylint` actions to `3.9` to ensure compatibility with the latest Ubuntu version.
Fixes #582
> ci: update Ubuntu version for GitHub actions

- doc/components/job-usage-calculation.rst
- doc/index.rst
The flux-accounting documentation doesn't have a section dedicated to explaining how job usage calculation works for an association.
---
This PR creates a page on flux-accounting's ReadTheDocs site to explain how job usage calculation works with a simple example for calculating an association's historical job usage value.
> doc: add job-usage calculation section

- doc/components/projects.rst
- doc/index.rst
There is no documentation in flux-accounting talking about how to configure and use projects for associations and how to submit jobs or view completed job records using projects.
---
This PR adds a new page to flux-accounting's ReadTheDocs site which outlines what projects are used for, how to configure them, and how to submit and view jobs by project.
> doc: add "Projects" page

- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1024-flux-account-queues.t
The `view-queue` command defines its own formatting for the output, but flux-accounting now has a common `AccountingFormatter` class that is uniform across all of the `view-*` commands.
---
This PR creates a new `QueueFormatter` subclass to use for printing out queue information from the flux-accounting database. I've also added some basic sharness tests for testing the output of calling `view-queue`.
> python: create new `QueueFormatter` class, refactor `view_queue()` to use new class

- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1024-flux-account-queues.t
There is no way to concisely list a set of defined queues in the flux-accounting database, similar to the `list-banks` and `list-projects` commands.
---
This PR adds a new command to the command suite called `list-queues`, which will list all of the queues defined in the `queue_table`. It offers the same options as `list-banks` to customize the output.
I've also added a couple of basic tests that call `list-queues` both in JSON and in a table format with customization.
> cmd: add `list-queues` command

- doc/guide/sanity-checklist.rst
- doc/index.rst
flux-accounting contains a guide for setting up flux-accounting, but it does not contain any documentation for checking that the various components of flux-accounting are up, configured, and running correctly.
---
This PR adds a short "Health/Sanity Checklist" to flux-accounting that walks through checking the various components of the accounting system and making sure it is running as expected.
Fixes #591
> doc: add health/sanity checklist for flux-accounting

- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
- t/python/t1006_job_archive.py
As noted in #593, the past usage factors for an association are not actually getting calculated and applied to associations and in the flux-accounting database because the `UPDATE` statements are not being `commit`ted in the `apply_decay_factor ()` function. The iteration through usage periods is also incorrect because the `for`-loop is starting at the wrong index; it *should* be starting at the first index and going to the second-to-last index instead of starting at the *second* index.
---
This PR changes the starting index for the `for`-loop in `apply_decay_factor()` to start at the *first* index instead of the second. It also adds a `commit()` statement near the end of the function to actually apply the `UPDATE` statements that are executed in the flux-accounting database. Finally, a …
> `apply_decay_factor ()`: fix iteration through usage periods, actually `commit` SQL statements

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1051-list-users.t
As noted in #596, there is no way to list any of the rows in the `association_table`, similar to the `list-banks` command. It would also be nice if the table could be filtered by certain columns in the table, such as by queue, project, or limit.
---
This PR adds a new command to the flux-accounting command suite called `list-users`, which by default will list all of the rows in the `association_table` in a human-readable table format. An optional `--json` argument is also added to output the results in a JSON format:
```console
$ flux account list-users
username | bank | default_bank | shares
---------+------+--------------+-------
user1    | A    | A            | 1     
user2    | A    | A            | 1     
user2    | B    | A            | 1     
user3    | B    | B            | 100 …
```
> cmd: add new `list-users` command

- src/bindings/python/fluxacct/accounting/__init__.py.in
- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/Makefile.am
- t/t1052-mf-priority-queue-limits.t
The priority plugin does not support enforcement of a max running jobs limit in a queue for an association, i.e the only max running jobs limit currently enforced for an association is one across _all_ of their running jobs, regardless of queue.
---
This PR looks to add enforcement of a new limit to the priority plugin: max running jobs in a queue per-association. To achieve this, new members are added to the `Queue` class and the `Association` class:
* `max_running_jobs`: the max number of running jobs an association can have in a queue
* `queue_usage`: a hash-map storing the name of the queue and the number of running jobs the association has in that queue
* `queue_held_jobs`: a hash-map storing the name of the queue and a list of any held jobs the association has in that queue
If a …
> plugin: add enforcement of max running jobs limit for a queue per-association

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1007-flux-account-users.t
- t/t1023-flux-account-banks.t
- t/t1024-flux-account-queues.t
- t/t1051-list-users.t
There is no way to customize the output of a query to the flux-accounting DB using a Python format string. It would be nice if
flux-accounting offered a way to customize the output with a format string, similar to a lot of the commands offered by flux-core.
---
This PR adds a new method to the `AccountingFormatter` class called `as_format_string()`, which will return the results of a query to the flux-accounting DB as a formatted string. As a result, the `view-*` and `list-*` commands now offer an `-o/--format` optional argument, which allows the user to pass in a formatted string to customize their output:
```console
$ flux account view-user -o "{userid:<8} | {bank:<12}" user5011
userid   | bank        
5011     | A
```
I've also added some basic tests for the commands that now have this …
> `view-*`/`list-*` commands: add `-o/--format` optional argument

- src/bindings/python/fluxacct/accounting/formatter.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1025-flux-account-projects.t
The `view-project` and `list-projects` commands manually define their own formatting for their respective commands, which is different from the rest of the command suite, which are subclasses of a common `AccountingFormatter` class to standardize all output.
The `view-project` and `list-projects` commands also do not take an optional `-o/--format` argument to format the output using a Python format string, which is inconsistent with the rest of the flux-accounting command suite.
---
This PR adds a new `ProjectFormatter` subclass to the Python bindings so that the output of the `view-project` and `list-projects` commands are standard with the rest of the flux-accounting command suite. I've also added `--table` and `--fields` options to the `list-projects` command and a `--parsable` option …
> bindings: add `ProjectFormatter` subclass, `-o/--format` options to `view-project`/`list-projects`

- src/plugins/mf_priority.cpp
- t/t1052-mf-priority-queue-limits.t
The `dependency_add ()` calls in the callback for `job.state.depend` are a little tough to read in the case that an exception needs to be raised because they are broken up over multiple lines to follow the 80 character-per-line limit. As more dependencies are added to this callback, this function will get even longer and perhaps more tedious to read through.
---
This PR adds an `error` label to the `job.state.depend` callback that is called when adding a dependency fails. It moves the `flux_jobtap_raise_exception ()` call to this label and sets the name of the dependencies before going there to include it in the exception message.
I've also moved a comment to below one of the `if`-statements as well as removed an errant `return 0` from one of the dependency checks in `job.state.depend`.
> plugin: clean up error handling, comments in `job.state.depend` 

- NEWS.md
There are no release notes for flux-accounting `v0.43.0`.
---
This PR adds some release notes.
> NEWS: add release notes for `v0.43.0`

- src/Makefile.am
- src/plugins/Makefile.am
- src/plugins/accounting.hpp
- src/plugins/job.cpp
- src/plugins/job.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/job_test02.cpp
As more and more flux-accounting dependencies are added to the priority plugin, it will be harder to keep track of certain attributes about jobs (and subsequently track them against an association's flux-accounting limits) without having to unpack those attributes in multiple callbacks. This gets cumbersome and makes tracking an association's jobs and limits very tedious.
---
This PR attempts to begin to alleviate this by adding a new `Job` class to be compiled with the rest of the plugin. A `Job` object stores things like the job's ID, counted resources, and any flux-accounting dependencies added to the job. Helper functions to check a job's resources and list of dependencies are also added to this class.
The goal with this class to eventually convert the `job.state.depend` and …
> plugin: add a new `Job` class 

- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
The `Queue` class definition is below the `Association` class definition, but there will eventually be a need to pass a `Queue` object to method(s) in the `Association` class. There is also no default initialization for the attributes of a `Queue` object. Additionally, the `Queue` class has no attribute for the name of the queue, which would be nice to have.
---
This PR moves some macro definitions as well as the `Queue` class definition to the top of the `accounting.hpp` file. It also adds a `name` attribute to the `Queue` class as well as add some default values to the existing attributes. As a result, I've adjusted the callback in the plugin that unpacks queue information from the flux-accounting DB as well as some unit tests to also include the name of the queue.
I've also added a …
> plugin: improve `Queue` class

- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- t/t1024-flux-account-queues.t
A queue can be deleted from the `queue_table` but still be referenced by associations in the `association_table`, i.e. an
association can still list that queue in its `queues` column. An admin who calls the `delete-queue` command should be warned that they should also edit any association rows in the `association_table` to account for deleting a queue.
---
This PR adds a check in `delete_queue()` to see if any associations have the queue being deleted still referenced in their `queues` attribute. If so, it issues a warning statement letting the admin know they should also edit any and all associations' rows to account for deleting a queue.
I've also added a basic test to make sure that the warning statement gets issued when removing a queue still referenced by an association.
> `delete-queue`: add warning statement when deleting a queue still referenced by associations

- doc/man1/flux-account-view-bank.rst
- doc/man1/flux-account-view-user.rst
The `view-bank` and `view-user` man pages do not list the `-o/--format` optional argument in the command descriptions which was added in #600.
---
This PR adds the `-o/--format` optional argument to both the `view-bank` and `view-user` man pages.
> view-* man pages: add -o/--format optional arg

- src/bindings/python/fluxacct/accounting/formatter.py
The `construct_hierarchy ()` method uses column indices instead of column names when placing the results of a SQL query into the string constructed for a flux-accounting bank/user hierarchy. This makes the code hard to parse and understand exactly what fields are being placed where in the string.
---
This PR changes the column indices to instead use column names when accessing the results of a SQL query and formatting the resulting string.
> `construct_hierarchy ()`: use column names

- src/Makefile.am
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- src/plugins/test/dependencies_test03.cpp
The priority plugin has to manually extract and check info about both the job and the association that is submitting the job for
any potential flux-accounting limits in both `job.state.depend` and `job.state.inactive`. As more and more dependencies are added to keep track of in flux-accounting, it will get more cumbersome to have to do these checks in the callbacks without the use of a `Job` object that can store this information across multiple callbacks.
---
This PR changes the how `job.state.depend` and `job.state.inactive` callbacks handle adding & removing dependencies from jobs as they encounter various (and future) flux-accounting limits. It condenses the need to store held jobs _both_ in a vector of just job IDs and a map that stores which job IDs are stored with which queue into …
> plugin: improve how dependency logic works with new `Job` class

- doc/man1/flux-account-add-user.rst
- src/bindings/python/fluxacct/accounting/db_info_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
The `fairshare` attribute for associations is not configurable in the `add-user` command, meaning that every association that gets added to the flux-accounting database **has** to have a `fairshare` value of 0.5. There might be a case where an admin might want to add an association with a different fairshare value, but in order to do this, they have to
open a SQLite shell, connect to the DB, and execute a SQL statement.
---
This PR adds `fairshare` as an optional argument to the `add-user` command, which allows an admin to customize the `fairshare` value for an association if they want to. The default is kept at 0.5.
I've also added the optional argument to the `add-user(1)` man page.
> `add-user`: add `--fairshare` as an optional argument

- doc/Makefile.am
- doc/man1/flux-account-edit-user.rst
- doc/man1/flux-account-list-users.rst
- doc/manpages.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1051-list-users.t
The `list-users` command does not take `default_project` as an optional argument, but it would be nice to have in case a user wants to filter the table by `default_project`.
There is also no `man(1)` entry for the `list-users` command.
---
This PR adds `default_project` as an optional argument and fixes the docstring comment for the `list_users()` function. I've also added a man page for the command.
I also snuck in a minor spelling fix commit for the `edit-user(1)` page.
> `list-users`: add `--default-project` optional argument, man page

- doc/man1/flux-account-add-user.rst
It is not totally clear from reading `add-user(1)` that the first project listed will become the association's default project when passing `--projects` to the `add-user` command.
---
This PR just adds a note to the man page to clarify how the default project is set.
> `add-user(1)`: clarify how default project is set

- doc/man1/flux-account-add-user.rst
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/t1025-flux-account-projects.t
The `add-user` command does not have an option to specify a default project when adding an association for the first time. The
behavior currently is to pass a list of projects where the first one is treated as the default. It would be convenient to have an option to also just specify a default project by itself.
---
This PR (built on top of #618) adds a new optional argument to the add-user command: `--default-project`, which takes a string representing the name of the default project an association will submit jobs under. It checks for the existence of this argument when determining the default project for an association before taking the first project listed in `projects` to keep backwards compatibility.
It a default project is specified, it makes sure that it is also present in …
> `add-user`: add `--default-project` as an optional argument

- src/cmd/flux-account.py
As mentioned in #620, the stack traces for errors raised in the flux-accounting commands are not suppressed by default even though a lot of the commands have custom error messages. This means that when an expected error occurs in flux-accounting (like adding a user to a bank that does not exist), the stack trace is very long and could be misleading to someone running the command.
---
This PR adds a decorator to `main()`  to enable suppression of large stack traces that prepend a custom error message raised from flux-accounting. Now, when an error occurs, the stack trace is suppressed and the error message looks more reasonable:
```console
$ flux account add-bank --parent-bank=foo B 1
flux-account: ERROR: error in add_bank: parent bank foo not found in bank table
```
Fixes #620
> `flux-account`: add `@CLIMain` decorator

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- t/t1007-flux-account-users.t
- t/t1023-flux-account-banks.t
A lot of the exception handlers in `flux-account-service.py` either have the wrong prefix or no prefix at all. Now that
flux-accounting has better formatting for printing out error messages (i.e. it disables the huge stack trace by default), it should take better care of making sure that error messages raised by flux-accounting have an appropriate format.
---
This PR standardizes the prefixes in the exception handlers for the different commands in the flux-accounting service. For functions in the Python bindings that have the command prefix in their `except` block, I've removed them, since they are now all located in `flux-account-service.py`.
I've also removed the prefix for the general `Exception` block since it was pointed out in #597 that a function could in fact return an `OSError`.
> `flux-account`: standardize prefixes for error messages

- NEWS.md
There are no release notes for `v0.44.0`.
---
This PR adds some release notes. I will wait to see if I can get #622 landed before landing this one. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.44.0 -m "Tag v0.44.0" && git push upstream v0.44.0
```
> NEWS: add release notes for `v0.44.0`

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
As noted in #624, a lot of the bindings still have `try/except` blocks from when flux-accounting did not have a systemd service and something that could actually catch any exceptions raised from the functions themselves. Thus, there is a lot of code in the bindings that looks like:
```python
except Exception:
raise Exception
```
Now that the flux-accounting service has a more robust way of capturing and propagating errors that occur, these bindings should be refactored to just `raise` the exception.
---
This PR removes a lot of the `try/except` blocks in the python bindings that do not provide a custom error message and just re-`raise`s the error to the service.
I've also moved one of the multi-line comments that describes some of the reasons for `sqlite3.Error`s to the service since the …
> bindings: remove redundant `try/except` blocks

- .gitignore
- etc/.gitignore
There are a number of files that are flagged by git as untracked files but can safely be ignored, such as editor-specific files and `.service` files in the `etc/` directory.
---
This PR adds these files to `.gitignore`.
> `.gitignore`: add files to `.gitignore`

- doc/man1/flux-account-list-banks.rst
- doc/man1/flux-account-list-queues.rst
- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/python/t1008_banks_output.py
- t/t1024-flux-account-queues.t
- t/t1025-flux-account-projects.t
The `list-users` command outputs in a table format by default, which was discussed by multiple Flux developers to be the preferred default (see https://github.com/flux-framework/flux-accounting/pull/597). However, the rest of the `list-*` command outputs in JSON by default instead of in a table format.
---
This PR changes the default behavior for the `list-*` commands to output in a table format by default instead of JSON format to match the `list-users` command.
I've also adjusted tests and man pages to reflect the change in the behavior for these commands.
> `list-*` commands: make table output default

- .github/workflows/main.yml
- t/Makefile.am
The flux-accounting `codecov` action is out-of-date and needs to be updated.
---
This PR upgrades the `codecov-action` to v5.
> github: upgrade codecov-action to v5

- src/bindings/python/fluxacct/accounting/create_db.py
- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
The `create-db` command logs status of creating tables in the flux-accounting database, but it uses the root logger instead of one custom to the module.
The log messages in the `update-usage` command don't include a timestamp of when those messages were actually logged, which might make analyzing run times of the `update-usage` command more difficult in the future.
---
This PR changes the `create-db` command to use a logger as a constant and uses it to log the status of creating various tables in the flux-accounting DB. I've also configured the logger in `update-usage` to prefix its log messages with a datetime.
> python: improve logger format in `update-usage`, create module-level logger in `create-db`

- doc/Makefile.am
- doc/man1/flux-account-add-project.rst
- doc/man1/flux-account-delete-project.rst
- doc/man1/flux-account-list-projects.rst
- doc/man1/flux-account-view-project.rst
- doc/manpages.py
There are no man pages for the various commands that deal with projects.
---
This PR adds `man(1)` pages for all of the commands that deal with projects.
> doc: add `man(1)` for project commands

- NEWS.md
There are no release notes for `v0.45.0`.
---
```
git tag -a v0.45.0 -m "Tag v0.45.0" && git push upstream v0.45.0
```
> NEWS: add release notes for v0.45.0

- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- t/Makefile.am
- t/t1054-mf-priority-bank-priorities.t
Banks can now have an associated floating-point priority assigned to them, but they are not utilized anywhere in the plugin.
---
This PR unpacks the priority associated with a bank and utilizes it when calculating the priority for a job. If the bank is updated while a job is still pending, the plugin will unpack the new associated priority and use it when re-calculating the overall priority for a job.
I've added a new set of tests that simulate submitting jobs under multiple banks with different priorities to showcase how a job's priority can be affected depending on how bank priorities are configured. There is also an example in there of a job's priority changing as the result of updating their bank while the job is still pending.
Fixes #642
> plugin: utilize `bank` priority when calculating priority for a job

- NEWS.md
flux-accounting has no release notes for `v0.46.0`.
---
This PR adds some release notes ahead of tomorrow's release. Once this lands, I'll create an annotated tag with the following:
```
git tag -a v0.46.0 -m "Tag v0.46.0" && git push upstream v0.46.0
```
> NEWS: add release notes for `v0.46.0`

- src/cmd/flux-account-service.py
The flux-accounting service uses direct dict key access to fetch parameters for the various flux-accounting functions. This can be problematic in the even that a key-value pair is not present in the payload (like in the case of an optional argument), and a `KeyError` will be raised.
---
This PR converts the direct key access in the payload dictionary to use `.get()`, which will return `None` in the case that a key-value pair does not exist in the dictionary instead of raising a `KeyError` exception. This makes using `.get()` standard across all of the flux-accounting commands defined in the service since right now some commands use `.get()` and some do not.
> flux-accounting service: use `.get()` instead of direct key access

- doc/Makefile.am
- doc/man1/flux-account-edit-factor.rst
- doc/man1/flux-account-list-factors.rst
- doc/man1/flux-account-reset-factors.rst
- doc/man1/flux-account-view-factor.rst
- doc/man1/flux-account.rst
- doc/manpages.py
There are no man pages for the commands that deal with viewing and modifying the priority factors in the flux-accounting database.
---
This PR adds `man(1)` pages for all of the commands that deal with viewing and modifying priority factor weights.
Fixes #664
> doc: add `man(1)` pages for priority factor commands

- doc/Makefile.am
- doc/components/limits.rst
- doc/guide/accounting-guide.rst
- doc/index.rst
There is a little description in the flux-accounting guide about on limits in the priority plugin, but it is incomplete (it is
missing the max resources per-association limit) and could use some more explanation and perhaps an example.
---
This PR adds a new page to the flux-accounting docs about how limits work in flux-accounting. It provides an example on the difference between soft limits and hard limits and creates a reference to the new "Limits" page in the flux-accounting guide.
Fixes #666
> doc: add new "Limits" page

- doc/Makefile.am
- doc/components/job-priorities.rst
- doc/guide/accounting-guide.rst
- doc/index.rst
- doc/man1/flux-account-jobs.rst
- doc/man1/flux-account.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/bindings/python/fluxacct/accounting/priorities.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1057-flux-account-jobs.t
There is no way to see a convenient breakdown of how various job priorities for an association are calculated. Since there are multiple factors with different weights, it might be helpful to list this breakdown on the command line instead of making someone consult documentation and calculate the priorities themselves.
---
This PR (built on top of #673) adds a new command called `jobs`, which takes one argument (`username`) and lists a breakdown of all of their jobs' priorities:
```console
JOBID          USER     BANK    BANKPRIO  BANKFACT  QUEUE   QPRIO  QFACT  FAIRSHARE FSFACTOR  URGENCY URGFACT PRIORITY
foEvbno        moussa1  A       100.0     1000      bronze  1      10000  0.99      100000    16      1000    209000  
fqyZGwh        moussa1  B       10.0      1000      bronze  1 …
```
> commands: add new `jobs` command to view priority breakdowns of jobs

- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
The `apply_decay_factor()` helper function has a `.commit()` call at the end of the function, which will write all changes to disk. However, this helper function is called in the middle of a SQLite TRANSACTION, which will already call `.commit()` when the transaction is finished running. Thus, this hinders performance of the `update-usage` command by performing an extra write to disk for every association in the `association_table`.
---
This PR removes the extra `.commit()` from the end of `apply_decay_factor()`.
> update-usage: remove extra `.commit()` from helper function

- doc/Makefile.am
- doc/man1/flux-account-view-job-records.rst
- doc/man1/flux-account.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/cmd/flux-account.py
- t/t1043-view-jobs-by-bank.t
There is no `man(1)` page for the `view-job-records` command.
---
This PR adds one.
> doc: add `man(1)` page for `view-job-records`

- doc/guide/accounting-guide.rst
- src/Makefile.am
- src/cmd/flux-account-service.py
- src/cmd/flux-account-update-usage.py
- src/cmd/flux-account.py
- t/t1006-update-fshare.t
- t/t1011-job-archive-interface.t
- t/t1026-flux-account-perms.t
- t/t1036-hierarchy-small-no-tie-db.t
- t/t1037-hierarchy-small-tie-db.t
- t/t1038-hierarchy-small-tie-all-db.t
- t/t1049-issue580.t
- t/t1053-issue631.t
As mentioned in #655, the `update-usage` command is a part of the flux-accounting service, which means that when it is running (especially on a large flux-accounting DB that can take a lot of time), it will halt the execution of other flux-accounting commands (even ones that just read from the DB) until the `update-usage` command finishes running. This command should be moved to its own script that establishes a separate connection to the DB so other flux-accounting commands can run while job usage values are being updated.
---
This PR creates a new Python command script in the `src/cmd/` directory called `flux-account-update-usage.py`, a script that will just call `update_job_usage()`, pretty much exactly similar to what the `update-usage` command in the flux-accounting service was …
> job-usage update: move update out of flux-accounting service and into own script

- doc/Makefile.am
- doc/man1/flux-account-show-usage.rst
- doc/man1/flux-account.rst
- doc/manpages.py
- doc/test/spell.en.pws
- src/bindings/python/fluxacct/accounting/Makefile.am
- src/bindings/python/fluxacct/accounting/visuals.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/python/t1012_visuals.py
- t/t1058-flux-account-visuals.t
Some of the numerical data in flux-accounting, such as job usage, would be cool to be visualized and compared directly on the command line for admins or users who are interested in looking at what users or banks are consuming the most usage. This would be a lot more convenient than calling `list-users` or `list-banks` and manually parsing tables to look at this kind of data.
---
This PR adds a new class to the Python bindings (`RenderBarChart`) that can create a horizontal bar chart using data from the flux-accounting database. To start, there are just two subclasses: classes for displaying the top _n_ associations or top _n_ banks in terms of job usage.
A new command is added to the flux-accounting command suite called `show-usage`, which will render a graph for either associations or …
> database: add graph commands for displaying job usage values for associations, banks

- NEWS.md
There are no release notes for `v0.47.0`.
---
This PR adds some release notes for `v0.47.0`. Posting this a little earlier (but planning on release date being next Monday) because next week is a short week. Once this lands, I'll push an annotated tag with the following:
```
git tag -a v0.47.0 -m "Tag v0.47.0" && git push upstream v0.47.0
```
> NEWS: add release notes for `v0.47.0`

- src/bindings/python/fluxacct/accounting/user_subcommands.py
There is a `.commit()` call in the `add_user()` function that is not needed since there is a `.commit()` call a few lines later.
---
This PR removes the extra `.commit()` call.
> `add-user`: remove extra `.commit()` when `INSERT`-ing values into `association_table`

- src/plugins/mf_priority.cpp
There are some arguments in the definition for `priority_calculation ()` that are no longer used with the abstraction of some functionality, such as looking up user accounting information, that I never removed.
---
This PR removes these unused function arguments from `priority_calculation ()`.
> plugin: remove unused function arguments from `priority_calculation ()`

- src/plugins/mf_priority.cpp
There is a line in the callback for job.state.run that is longer than 80 characters, which does not follow the coding guidelines outlined in [RFC 7](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_7.html).
---
This PR just shortens the line to be at less than 80 characters.
> plugin: shorten line that is greater than 80 characters

- doc/components/database-administration.rst
As mentioned in #697, there is some confusion about having to reference usernames and bank names by their exact case, i.e. using capital letters for bank names that contain a capital letter, and there is no documentation making this clear for users and/or administrators.
---
This PR adds a note to the Database Administration document about case sensitivity and being careful about including capital letters in usernames or bank names.
Fixes #697
> doc: add note about case sensitivity for names

- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/accounting_test01.cpp
- src/plugins/test/dependencies_test03.cpp
- t/Makefile.am
- t/t1052-mf-priority-queue-limits.t
- t/t1060-mf-priority-queue-usage.t
The `queue_usage` attribute of the `Association` class currently _only_ keeps track of the queue an association is running their jobs under and how many running jobs they have under that particular queue. However, there is also a need to know how many resources (i.e. nodes) an association has across all of their running jobs under that queue, which the plugin does not currently keep track of.
---
This PR changes the `queue_usage` attribute of the `Association` class to instead be a map where the key remains the same (a string containing the name of the queue) but with a value of a new `QueueUsage` class, a class that tracks both an association's number of currently running jobs as well as their total node usage across all of their running jobs in that queue. Node usage per-queue is now …
> plugin: add `QueueUsage` class to track an association's node usage per-queue

- doc/components/limits.rst
- src/Makefile.am
- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/queue_limits_test05.cpp
- t/Makefile.am
- t/t1062-mf-priority-queue-resource-limits.t
The plugin needs a way to enforce a per-queue max nodes limit when an association is using up a lot of nodes across their running jobs under a particular queue.
---
This PR adds limit enforcement on the max number of nodes an association can have across all of their running jobs in a particular queue. It adds a method to the `Association` class to check if their submitted job would put them _over_ the queue's max nodes limit, and if it does, a dependency is added to the job until a currently running job in that queue completes.
Unit tests are added for checking the new `under_queue_max_resources ()` method and sharness tests are added for simulating different scenarios where an association hits the per-queue max nodes limit as well as any other potential limits at the same time.
Fixes …
> plugin: add enforcement of a per-queue max nodes limit

- src/bindings/python/fluxacct/accounting/sql_util.py
- src/cmd/flux-account-priority-update.py
- src/cmd/flux-account-service.py
The `flux-account-priority-update.py` and `flux-account-service.py` files each have their own check of the DB schema version of the flux-accounting database. Thus, there is opportunity to create a function that can be imported and used across the flux-accounting scripts.
In the case of `flux-account-service.py`, the `check_db_version()` function it had defined is not even being used. 🤦
---
This PR creates a function which will just return the schema version number of the flux-accounting DB, and uses this function both in `flux-account-priority-update.py` and `flux-account-service.py`.
> bindings: add `db_version()` function, use it across scripts that check DB version

- doc/components/job-usage-calculation.rst
- doc/man1/flux-account-view-user.rst
- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/python/t1002_user_cmds.py
- t/t1011-job-archive-interface.t
An association's job usage value is made up of multiple job usage values (i.e. it is the sum of both current and older job usage factors that are stored in `job_usage_factor_table`), but this data is not viewable on the command line.
---
This PR adds a new optional argument to the view-user command: `-J/--job-usage`, which will return all the data stored for an association in `job_usage_factor_table`. Docs are updated with a description of the optional argument itself as well as an example of how to use it.
> `view-user`: add `-J/--job-usage` optional arg

- NEWS.md
There are no release notes for `v0.48.0`.
---
```console
git tag -a v0.48.0 -m "Tag v0.48.0" && git push upstream v0.48.0
```
> NEWS: add release notes for `v0.48.0`

- src/plugins/job.cpp
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1063-issue709.t
The priority plugin does not reject jobs in `job.validate` if it exceeds a max resources limit  either per-association or per-queue, and instead will hold the job in `DEPEND`, even though the job is not waiting for a currently running job to finish running. It instead should reject the job during validation with a message saying that the job size is greater than the limit defined per-association or per-queue.
---
This PR adds a check in `job.validate` to compare the size of the job to both the association's `max_nodes` or `max_cores` limits and the queue's `max_nodes_per_association` limit, and if the job would exceed any of these limits, the job is rejected.
Some tests that reproduced the original issue are added to ensure that a job is rejected in `job.validate` instead of held if it …
> plugin: reject jobs that exceed an association's or queue's max resources limits

- src/bindings/python/fluxacct/accounting/formatter.py
The HierarchyFormatter class is not used anywhere in the Python bindings (and was mistakenly left in when merging #676 - sorry about that!).
---
This PR removes it (and its associated imports) from `formatter.py`.
> formatter: remove `HierarchyFormatter` class

- src/bindings/python/fluxacct/accounting/job_usage_calculation.py
- t/python/t1006_job_archive.py
- t/scripts/query.py
- t/t1011-job-archive-interface.t
The `calc_usage_factor()` issues a `SELECT` query on the `"jobs"` table for *every* user in the `association_table`. If there are lots and lots of associations in the table (and subsequently, lots and lots of job records in the `"jobs"` table), these read operations become very expensive and drastically slow down the performance of the job usage update.
---
This PR moves and adjusts the `SELECT` query out of the `calc_usage_factor()` function and put it before the `for-loop` is started to update the job usage values for all of the associations. It adjusts the `SELECT` query to run just *once* instead of for every association by performing a `LEFT JOIN` on the `jobs` table and creating joint rows for associations and any new
jobs they may have ran since their last seen job. These rows are …
> `update-usage`: remove `SELECT` query on `jobs` table for every association

- doc/man1/flux-account-view-bank.rst
- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/formatter.py
- src/cmd/flux-account-service.py
- src/cmd/flux-account.py
- t/Makefile.am
- t/t1066-view-bank-concise.t
When viewing the job usage breakdown for a particular bank in the flux-accounting DB, it can get easily cluttered with many associations who don't actually have any job usage contributing to the bank's total job usage value. It would be nice if the `view-bank` command had a filter to only show associations who contributed to the bank's total job usage value.
---
This PR adds a new `-c/--concise` option to the `view-bank` command, which will only list associations under that bank which have a job usage value greater than 0.
This will reduce output that could potentially has a lot of noise, like the following:
```console
$ flux account view-bank -t root
Bank                            Username           RawShares            RawUsage           Fairshare
root …
```
> `view-bank`: add `-c/--concise` option

- NEWS.md
There are no release notes for `v0.50.0`.
---
This PR adds some release notes. Once this has landed, I'll go ahead and create an annotated tag with the following:
```console
git tag -a v0.50.0 -m "Tag v0.50.0" && git push upstream v0.50.0
```
> NEWS: add release notes for `v0.50.0`

- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- src/plugins/test/queue_limits_test05.cpp
- t/Makefile.am
- t/t1067-mf-priority-issue733.t
As mentioned in #733, when checking to see if an association is under a queue's max resources limit for a particular job, the "queues" map gets initialized with a `Queue` object unintentionally (especially if queues are not configured in the flux-accounting DB), and subsequently submitted jobs get rejected with a `"Queue not valid for user"` error message.
---
This PR reworks the `under_queue_max_resources ()` method to perform a safer lookup of the "queues" map with the passed-in queue instead of passing the queue directly in the map (which will initialize the map if the queue does not already exist). It adjusts the calls to this method to account for the change in which parameters are passed to `under_queue_max_resources ()`. I've added a simple test file to ensure that configured …
> plugin: don't initialize "queues" map when checking limits

- NEWS.md
There are no release notes for `v0.51.0`.
---
This PR adds some release notes for `v0.51.0`, which contains the fix proposed in #734. Once this has landed, I will create an annotated tag with the following:
```console
git tag -a v0.51.0 -m "Tag v0.51.0" && git push upstream v0.51.0
```
> NEWS: add release notes for `v0.51.0`

- src/plugins/accounting.cpp
- src/plugins/accounting.hpp
- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1068-mf-priority-queues-projects-query.t
The information stored in the priority plugin's `queues` map and `projects` vector are not returned in the output of `flux jobtap query`, which makes it difficult to diagnose what queue and/or project information the plugin has on hand without inserting print statements directly within the plugin.
---
This PR adds the information stored in the `queues` map and the `projects` vector to the information returned in the output of `flux jobtap query`. It adds helper functions to construct and pack the objects into JSON objects, similar to how `Association` objects are already constructed for the output of `flux jobtap query`.
I've added some basic tests to check for both queue and project information in the output of `flux jobtap query`.
Fixes #736
> plugin: add more information returned in output of `flux jobtap query`

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- t/t1051-list-users.t
The `list-users` command does not accept multiple values per filter. It would be nice if each filter could accept multiple values,
e.g. list associations that might belong to either bank1 OR bank2 OR bank3.
---
This PR extends the `list_users()` function to accept multiple values per filter by attempting to strip the value passed in for each filter and using the `"IN"` keyword to query `association_table` in the case where more than one value is passed per filter.
An example:
```console
flux account list-users --bank=A,B
creation_time | mod_time   | active | username | userid | bank | default_bank | shares | job_usage | fairshare | max_running_jobs | max_active_jobs | max_nodes  | max_cores  | queues             | projects                        | default_project …
```
> `list-users`: extend command to search for multiple values per filter

- src/bindings/python/fluxacct/accounting/util.py
- src/cmd/flux-account-update-usage.py
- t/t1011-job-archive-interface.t
The `flux account-update-usage` script logs _all_ messages (Including `INFO`-level) every time it runs, which can flood log files with information since it runs periodically with `flux cron`.
---
This PR adds an optional argument to `flux account-update-usage` called `--log-level`, which allows the user to enable `INFO`-level logging. Now, by default, only `WARNING`-level messages are logged.
Some basic tests calling `flux account-update-usage` with and without `-v/--verbose` to make sure `INFO`-level messages are correctly suppressed.
Fixes #750
> `update-usage`: add `-v/--verbose` option

- src/plugins/mf_priority.cpp
- t/Makefile.am
- t/t1070-issue749.t
The priority plugin does not consider that jobs held in `DEPEND` state could potentially have their limits removed if an association's or queue's limits have changed after an update. So, a job held in `DEPEND` will still remain in `DEPEND` even if it meets all of the conditions to run after a change to limits.
---
This PR adds an iteration through the plugin's internal map of associations when `flux account-priority-update` is called and checks the held jobs of every association to see if they meet any and all of the requirements to have its dependencies removed.
I've also added some tests that walk through each flux-accounting dependency and makes sure that a job held in `DEPEND` for each of these limits can proceed to run after changing the limits and pushing to the plugin with `flux …
> plugin: check dependencies of held jobs after `flux account-priority-update`

- src/bindings/python/fluxacct/accounting/user_subcommands.py
- src/bindings/python/fluxacct/accounting/util.py
`Cursor` objects are not explicitly closed in a number of the functions that are called that read from/write to the SQLite database. While not totally necessary (`Cursor` objects *should* be cleaned up by Python's garbage collectors), if there are lots of parallel processes that are reading and writing to the database (such as the flux-accounting service and the `priority-update` script), these `Cursor` objects can keep transactions alive and potentially lead to a database lock. It also would provide better code clarity if these functions actually explicitly cleaned up the use of these objects when the function completes.
---
This PR introduces the use of a context manager for the `Cursor` objects created in the Python bindings that interact with the flux-accounting database.
> python: explicitly close `Cursor` objects after use in user commands

- src/bindings/python/fluxacct/accounting/bank_subcommands.py
- src/bindings/python/fluxacct/accounting/project_subcommands.py
- src/bindings/python/fluxacct/accounting/queue_subcommands.py
- src/cmd/flux-account-fetch-job-records.py
In continuation of #768, `Cursor` objects are not explicitly closed in a number of functions that are called for a lot of the Python commands. Thus, these `Cursor` objects can keep transactions alive, which is a potential cause for a database lock.
---
This PR uses the context manager decorator introduced in #768 as well as the `contextlib.closing()` method to explicitly close `Cursor` objects when functions exit.
It also changes some of the `.execute()` statements to use the `Cursor` object instead of the `Connection` object, which should make it consistent for the rest of the Python bindings.
> bindings: close `Cursor` objects when function exits
